### ISSUE TITLE
Use class?

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/repr#1]
as initiated in IRkernel/IRkernel#82, there’s the question if we should use a dedicated class or not.

pro:
----

* repr objects are easily handled and identified
* we can create repr objects that will be passed unaltered. e.g. inside of a list or a dataframe

	…but that would only work for one format. therefore, to support prettyprinting of own classes, we’ll have to use custom classes with several `repr_*` methods to support multiple formats, anyway.

con:
----

* it messes with our implemention of the kernel using jsonlite

	…but that’s a very specific problem.

outlook
-----------

maybe create multi-repr objects that can be used for unaltered passing in dataframes?

**Comment by takluyver** [comment]
Why would we need to pass around repr objects?

The way the Python side works, the `_repr_html_`, `_repr_png_` etc. methods all just return plain unicode/bytes strings - the fact that they're coming from those methods is all we need. Then we have classes like `HTML` and `Image`, which *have* those special methods - so you can construct e.g. an `Image` object which may have png/svg/html etc. reprs, depending on various features.

**Comment by JanSchulz** [comment]
I also think that `repr_*` should return a string and that's it. The calling code can build a structure from it.

knitr uses a structure (but knitr doesn't track what mime type the content is) in it's `knit_asis` class:

```
asis_output = function(x, meta = NULL, cacheable = length(meta) == 0) {
  structure(x, class = 'knit_asis', knit_meta = meta, knit_cacheable = cacheable)
}
```

IMO that would be a nice example to extend knitr to use `repr` for building these structures.

**Comment by flying-sheep** [comment]
hmm, the R equivalent of the HTML and Image classes would be the same: custom classes with `repr_*` methods defined on them.

you’re right that currently there’s no need to use repr objects: recursive repr methods (like those on list and matrix/data.frame) just call repr on the list items/cells and concatenate the result in some way…

please think about it a bit though, i have a feeling we’re missing something…

**Comment by JanSchulz** [comment]
> recursive repr methods (like those on list and matrix/data.frame)

I don't think we should work on these: for a dataframe, we should have one `repr_markdown.data.frame`, which takes a dataframe and formats it via pander (see here what formatters are available: https://github.com/rstats-gsoc/gsoc2015/wiki/pander). For latex there is xtables and there is probably one package for html as well :-)

If one really wants to build a recursive `repr_html.list`, that's also possible but that one would have to construct the html itself by using `<table>`, an iteration over the elements with `"<tr><td>"+repr_html(element)+"</td></tr>"` and `</table>` (which could break if `repr_html(element)` would return something which is not valid in a `<td>`).

My definition: `repr_xxx.objecttype` is a function to turn an object of type `objecttype` into a string/bytes, which represents the object in the format `xxx` (aka markdown, html, png,...). It's equivalent to the `_repr_xxx_` method in class `objecttype` in python.

My only problem with this definition is that we can't really take over the `printr` usecase, which would return an 'asis' object, which can have metadata. but then, printr currently does not mark the mimetype and if that would be added it could be used to construct a generic  'asis' object without metadata.

**Comment by flying-sheep** [comment]
actually i did something in a python notebook that was really awesome and depended on recursive representations:

i created a pandas DataFrame with one column containing HTML instances with links in it (dynamically generated from pubmed IDs). this was very very useful for what i did.

---

what do you think should `repr_*.list` do? create pretty list headers list with plain text representations of the list entries? that’s just inconsistent.

> which could break if `repr_html(element)` would return something which is not valid in a `<td>`

what would that be?

**Comment by JanSchulz** [comment]
> what would that be?

No idea if that realistic, but AFAIK getting a complete html document (`<html>...</html>`) would not result in a valid `<table>...</table>`.

**Comment by takluyver** [comment]
I don't think the results of repr_html (in R or Python) should ever contain `<html>` or `<body>` tags - they should always be HTML fragments, not a complete document. I'm sure it's still possible to come up with something that breaks inside a table, though - even if the HTML is acceptable, the visible result may not be. But that seems like an acceptable risk for now.

For recursion, I would leave it up to the container object's own `repr_html.somecontainer` method to do something like:

```R
item_html = repr_html(item)
if (is.null(item_html)) {
    item_html = repr_text(item)
}
```

**Comment by flying-sheep** [comment]
yeah.

so the consensus is: remove classes and `repr.format`, leave everything else like it is?

**Comment by takluyver** [comment]
I think so. Let's see what the code looks like after that.
