### ISSUE TITLE
Setting data.table column outputs whole table to screen

### ISSUE THREAD

**Issue by abielr** [IRkernel/repr#109]
If I run the code below, the second line will cause the entire `dat` object to be output, whereas at an R console it wouldn't return anything. The syntax used is the special syntax for setting columns with the popular `data.table` package. I'm using the 1.9.5 devel version of `data.table`. 

```
library(data.table)
dat <- data.table(x1=1:10)
dat[, x2 := 1:10]
```

**Comment by flying-sheep** [comment]
Fixed according to Rdatatable/data.table#933
