### ISSUE TITLE
Feature request: display column type and dimensions

### ISSUE THREAD

**Issue by aguang** [IRkernel/repr#113]
This is in reference to #112.

With the **tibbles** package in R when you print out a tibble you get:
 * Output truncated to the first 10 rows and however many columns fit on the page
 * The typing of each column's values
 * The dimensions of the full tibble

Currently when I print out a tibble in Jupyter notebooks I get the full output as well, formatted the same as if it was a data frame. Based on #112 that is by design, but it would be nice to be able to get the typing and dimensions as well.

**Comment by flying-sheep** [comment]
All the code for this is in [repr_matrix_df.r](https://github.com/IRkernel/repr/blob/master/R/repr_matrix_df.r).

What’s needed here would be

1. distinguish between homogeneous and heterogeneous 2D data (matrices vs data frames)
2. come up with a way to display both

    I think data frames should get a second header column with the column types, and both should get a [caption](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption) with the dimensions. A matrix’ caption should also contain its type

Do you agree? Should I use tibble’s 3-letter type abbrevations? How do tibbles display more uncommon column types like datetimes, durations, nested dataframes, …?

**Comment by aguang** [comment]
I think it sounds good. I am not entirely sure how tibble displays more uncommon column types, it appears to display datetimes as `dttm` and some S3 or S4 objects as `S4: xyz` but for other S3 or S4 objects will show typing as a list with the values inside as S3 or S4 objects. It appears to be an issue in the tibble package as well: tidyverse/tibble#326.

```{r}
> library(lubridate)
> library(tidyverse)
> tibble(make_datetime(today(),5,5))
# A tibble: 1 x 1
  `make_datetime(today(), 5, 5)`
  <dttm>                        
1 17948-05-05 00:00:00   

> tibble(as.duration(1))
# A tibble: 1 x 1
  `as.duration(1)`
  <S4: Duration>             
1 1s     

> group_by(mpg, cyl, drv) %>% nest()
# A tibble: 9 x 3
    cyl drv   data             
  <int> <chr> <list>           
1     4 f     <tibble [58 × 9]>
2     6 f     <tibble [43 × 9]>
3     4 4     <tibble [23 × 9]>
4     6 4     <tibble [32 × 9]>
5     8 4     <tibble [48 × 9]>
6     8 r     <tibble [21 × 9]>
7     6 r     <tibble [4 × 9]> 
8     8 f     <tibble [1 × 9]> 
9     5 f     <tibble [4 × 9]> 

# ape is a phylogenetics package
> tibble(c(ape::rtree(2),ape::rtree(3)))
# A tibble: 2 x 1
  `c(ape::rtree(2), ape::rtree(3))`                                                                                                 
  <S3: multiPhylo>                                                                                                                  
1 3                , 3                , 1                , 2                , t1               , t2               , 0.4716983486432…
2 4                 , 5                 , 5                 , 4                 , 5                 , 1                 , 2        …
```

```{r}
> setClass("Person",slots=c(name="character",age="numeric"))
> jen<-new("Person",name="Jen Li",age=5)
> tibble(jen)
Error: All columns in a tibble must be 1d or 2d objects:
* Column `jen` is Person
Call `rlang::last_error()` to see a backtrace
> tibble(person=c(jen,jen))
# A tibble: 2 x 1
  person      
  <list>      
1 <S4: Person>
2 <S4: Person>
```

**Comment by flying-sheep** [comment]
The code lives in [pillar::type_sum](https://github.com/r-lib/pillar/blob/2d3bde1fb6a1df9dc203f34d8b527657ff36c00a/R/type-sum.R)

Maybe repr should depend on pillar and use it?

**Comment by aguang** [comment]
That sounds good to me. So basically, use output of `type_sum` as second header column. I agree with not using htmlTable or kable.

In terms of caption, since a lot more of the data frame (or matrix) will be printed I think it would be more useful to do `caption-side: top` instead so that the user can see the dimensions immediately.
