### ISSUE TITLE
Respect `options(max.print=x)`

### ISSUE THREAD

**Issue by terhorst** [IRkernel/repr#114]
Calling `display(v)` on a vector `v` prints every entry of `v`, regardless of length. This is very suboptimal when `v` is long, and typically renders the browser window unresponsive for minutes at a time. R's built-in console formatter has an option for controlling how much output it generates. The limit is set using `options(max.print=x)`, the default being `x=100000` I believe. Even this is pretty high and I typically set it to something like `x=100`. It would be nice if IRdisplay respected this parameter setting.

**Comment by flying-sheep** [comment]
There’s already options for matrices:

https://github.com/IRkernel/repr/blob/589b4ead37cd6fb3ddd6e438ddad3ae91ea41ba2/R/options.r#L67-L68

I think we should use our own option here, too.

**Comment by teng-gao** [comment]
Hi, did this get resolved for vectors? Seems like there's still no way to set the max print.

**Comment by flying-sheep** [comment]
You didn’t check the help page of the options …

```r
help('repr-options')
```

**Comment by teng-gao** [comment]
Ooo thanks!!
