### ISSUE TITLE
ERROR while rich displaying an object: Error in if (many_rows) {: argument is of length zero

### ISSUE THREAD

**Issue by ACC839303568** [IRkernel/repr#117]
Environment:
```
sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.3 tools_3.5.3   
```
```
installed.packages()[,c("Package","Version")]
             Package        Version   
base         "base"         "3.5.3"   
base64enc    "base64enc"    "0.1-3"   
boot         "boot"         "1.3-20"  
class        "class"        "7.3-15"  
cluster      "cluster"      "2.0.7-1" 
codetools    "codetools"    "0.2-16"  
compiler     "compiler"     "3.5.3"   
crayon       "crayon"       "1.3.4"   
datasets     "datasets"     "3.5.3"   
digest       "digest"       "0.6.18"  
evaluate     "evaluate"     "0.13"    
foreign      "foreign"      "0.8-71"  
graphics     "graphics"     "3.5.3"   
grDevices    "grDevices"    "3.5.3"   
grid         "grid"         "3.5.3"   
htmltools    "htmltools"    "0.3.6"   
IRdisplay    "IRdisplay"    "0.7.0"   
IRkernel     "IRkernel"     "0.8.15"  
ISLR         "ISLR"         "1.2"     
jsonlite     "jsonlite"     "1.6"     
KernSmooth   "KernSmooth"   "2.23-15" 
lattice      "lattice"      "0.20-38" 
MASS         "MASS"         "7.3-51.1"
Matrix       "Matrix"       "1.2-15"  
methods      "methods"      "3.5.3"   
mgcv         "mgcv"         "1.8-27"  
nlme         "nlme"         "3.1-137" 
nnet         "nnet"         "7.3-12"  
parallel     "parallel"     "3.5.3"   
pbdZMQ       "pbdZMQ"       "0.3-3"   
Rcpp         "Rcpp"         "1.0.1"   
repr         "repr"         "0.19.2"  
rpart        "rpart"        "4.1-13"  
spatial      "spatial"      "7.3-11"  
splines      "splines"      "3.5.3"   
stats        "stats"        "3.5.3"   
stats4       "stats4"       "3.5.3"   
survival     "survival"     "2.43-3"  
tcltk        "tcltk"        "3.5.3"   
tools        "tools"        "3.5.3"   
translations "translations" "3.5.3"   
utils        "utils"        "3.5.3"   
uuid         "uuid"         "0.1-2"   
```
jupyter notebook --version  5.7.8  (And was installed by Anaconda)
Anaconda 1.9.7
Windows 10 Pro

When I tried to execute the r program below on jupyter notebook it showed a mistake on the screen:
```
a1 <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
b1 <-ts(a1)
b1
```

```
ERROR while rich displaying an object: Error in if (many_rows) {: argument is of length zero

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. repr::mime2repr[[mime]](obj)
8. repr_text.ts(obj)
9. repr_ts_generic(obj, repr_text.matrix, ...)
10. repr_func(m, ..., rows = nrow(m), cols = ncol(m))
11. ellip_limit_arr(obj, ...)
12. arr_partition(a, rows, cols)
```
However, the program executed well on rstudio ,which showed that:
```
Time Series:
Start = 1 
End = 20 
Frequency = 1 
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
```
I tried to reinstall the whole r program and IRkernel by this:
```
install.packages('IRkernel') 
IRkernel::installspec(user = FALSE)
```
(See this https://irkernel.github.io/installation/)

Though successfully installed without any warnings and error, it still showed the error above on jupyter notebook. 

Still, I tried `devtools::install_github('IRkernel/repr')` and `install.packages(c('IRkernel', 'IRdisplay', 'repr'))`, but nothing worked for me. (See this https://github.com/IRkernel/repr/issues/100)

Few weeks ago it was nothing wrong with this problem and it did show right, but now it has this kind of exhausting problem……

I know that the jupyter notebook is nothing wrong without this as I executed `plot(b1)` and it did plot.

I don't know how to solve this problem……

**Comment by ACC839303568** [comment]
Add:
Few weeks ago I worked out without any problem
![image](https://user-images.githubusercontent.com/32789300/56372467-a43ea800-6231-11e9-8e36-7345db390f6f.png)

**Comment by ACC839303568** [comment]
Okay I got the way to solve this, by downgrading the `repr` package version.
You firstly uninstall the former `repr` package ( Should I show how? ), then reinstall it by entering this:
`install.version('repr','0.18')`
Then the problem is solved.

Please take this issue into consider cuz something wrong with the newest one, and I guess because of this (https://github.com/IRkernel/repr/issues/105)

……

**Comment by flying-sheep** [comment]
Thanks for reporting! The newest matter should fix this

**Comment by pmgh2345** [comment]
I just experienced this today- has this been addressed yet?

**Comment by flying-sheep** [comment]
As you can see 3cm above your message, it has been addressed in 505a052

**Comment by pmgh2345** [comment]
I'm sorry- I'm new to git and how it works so I didn't know what to look for. I've since researched how to apply this commit within conda, but I'm coming up short. Do you know of any resource that explains how to do it, and if not, might you kindly tell me what I'm supposed to type into the Anaconda prompt? Thank you for your time!

**Comment by flying-sheep** [comment]
You can bug them to upgrade the package, it’s been on version 1.0 for a while now. Or you just upgrade it normally: `install.packages('repr')`

**Comment by pmgh2345** [comment]
When I try to install it as you instructed (but through conda), conda only offers me the version I already have; that's why I figured I needed to somehow apply the commit directly from github.

**Comment by flying-sheep** [comment]
> but through conda

What do you mean? The normal way to install R packages it through CRAN. `install.packages('repr')` should install from CRAN: https://cran.r-project.org/package=repr

**Comment by pmgh2345** [comment]
I was referring to the fact that I am working on a jupyter notebook via anaconda, and as such, I was under the impression that all upgrades and package installations were to be done through conda which manages said packages and dependencies. That is why I was looking for a way to update repr in the conda shell, whether through downloading and applying the commit above or just updating repr. I had no such luck by either of those methods, so I tried to just install the package the normal R way you mention above in a jupyter notebook, and it seems to have ruined my entire install of anaconda (it is the only change I made since returning to my workstation and verifying that everything was working as it was before). I can't even load libraries in a jupyter notebook anymore- it just hangs whereas it used to load said libraries in about 5 seconds.

If you have any ideas for how to get whatever version/commit of repr that will work the r kernel in jupyter notebook, I would really appreciate it. FYI Conda says I am on the most recent version of repr available to it, and that was the one giving me the rich display error.

**Comment by flying-sheep** [comment]
Sure! The reason anaconda sometimes doesn’t have the latest version is that someone else maintains the packages there. Stuff on Bioconductor or CRAN is maintained by the authors.

If you want to use conda you should be aware of that, although I know it’s not a thing people advertising conda tell you. The [official install instructions](https://irkernel.github.io/installation/) for IRkernel don’t mention conda for a reason.

**Comment by pedritomelenas** [comment]
I stumbled upon a similar error, see https://github.com/r-cas/ryacas/issues/67. Reinstalling `repr` does not seem to solve the problem. 

This is my `sessionInfo()` output:

```
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /home/pedro/lib/R-4.2.2/lib/libRblas.so
LAPACK: /home/pedro/lib/R-4.2.2/lib/libRlapack.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Ryacas_1.1.3.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9      fansi_1.0.3     crayon_1.5.2    digest_0.6.31  
 [5] utf8_1.2.2      IRdisplay_1.1   repr_1.1.5      lifecycle_1.0.3
 [9] jsonlite_1.8.4  magrittr_2.0.3  evaluate_0.18   pillar_1.8.1   
[13] rlang_1.0.6     cli_3.4.1       uuid_1.1-0      vctrs_0.5.1    
[17] IRkernel_1.3.2  tools_4.2.2     glue_1.6.2      pkgload_1.3.2  
[21] fastmap_1.1.0   compiler_4.2.2  base64enc_0.1-3 pbdZMQ_0.3-8   
[25] htmltools_0.5.4
``` 
Thanks.
