### ISSUE TITLE
Help me please, IRkernel

### ISSUE THREAD

**Issue by myjuda** [IRkernel/repr#127]
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failed to install 'IRkernel' from GitHub:
  Command failed (1)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules https://github.com/jupyter/jupyter_kernel_test.git /var/folders/85/qy6xcss54xj5rc9gf54g20jr0000gn/T//RtmpKeGXBN/remotesbd8c1d6f975e/IRkernel-IRkernel-b9eea70/tests/testthat/jkt' had status 1

**Comment by flying-sheep** [comment]
Just install it using the official instructions please. Simply from CRAN. https://irkernel.github.io/installation/
