### ISSUE TITLE
Make display of row/col indices configurable

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/repr#14]
as shown here, matrix/data.frame display is inconsistent.

![](https://cloud.githubusercontent.com/assets/599274/9509001/9cb1aad6-4c20-11e5-90ac-6204ed38c9d3.png)

users should be able to configure if they want to see row and column indexes if no rownames or colnames exist or not.

**Comment by karldw** [comment]
The reason this happens is R auto-assigning row names to the data.frame.  I could work on this; what do you have in mind for user configurability?

**Comment by flying-sheep** [comment]
simply a `repr.matrix.forcenames`. it would either be a `logical(1L)` (force or don’t force both row and col names) or a `logical(2L)` (set forcing of row and col names separately)

option would be added [here](https://github.com/IRkernel/repr/blob/cf25f53440ed6f2469ff437c3b7b5bfec14d5926/R/options.r#L71-L73).

**Comment by karldw** [comment]
I think it would be nice to make repr's output mimic the output of a normal R session.  In some cases, like matrices, that might mean adding new names so repr displays them properly.
We could then have options to:
- not bother, keeping current behavior
- force no names at all
  - or force no row/col names
-  no auto-generated names (but maintain user-assigned column or row names)

To match R's normal output for matrices, we could assign names like this:
```R
> (x <- matrix(1:5))
     [,1]
[1,]    1
[2,]    2
[3,]    3
[4,]    4
[5,]    5
> rownames(x) <- paste0('[', 1:5, ',]')
> colnames(x) <- '[,1]'
> x
     [,1]
[1,]    1
[2,]    2
[3,]    3
[4,]    4
[5,]    5

```

**Comment by karldw** [comment]
I take it back, that seems like more work than benefit; if people want the default R output, they can always just call `print`.

How about defaulting to never displaying row names and displaying column names for all arrays except matrices?

**Comment by flying-sheep** [comment]
hmm, for arrays i don’t see why columns are special.

for data.frames, it’s a different story.

**Comment by karldw** [comment]
Oops, when I said "arrays" I meant two-dimensional objects with rows and columns, not realizing `array` is an entirely distinct R type.

So, how about:
For all objects where `length(dim(x))` is 2, except matrices, we default to displaying column names and hiding row names?  For matrices, we default to showing neither row nor column names.

**Comment by flying-sheep** [comment]
sure!

**Comment by flying-sheep** [comment]
Should be fixed by now
