### ISSUE TITLE
`repr_html` not working under R 4.1.1

### ISSUE THREAD

**Issue by renkun-ken** [IRkernel/repr#143]
Once I upgrade to R 4.1.1, `repr_html()` no longer works:

```r
hfile <- utils::help("get")
repr::repr_html(hfile)
```

```
Error in seq_len(head.end.idx) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(head.end.idx) : first element used of 'length.out' argument
Backtrace:
1: repr_help_files_with_topic_generic(obj, Rd2HTML)
2: repr_html.help_files_with_topic(hfile)
3: repr::repr_html(hfile)
```

Related: https://github.com/REditorSupport/languageserver/issues/468

**Comment by renkun-ken** [comment]
Looks like 

https://github.com/IRkernel/repr/blob/7f27d6a359c65e52ddee52a866c6a9f1999947f3/R/repr_help_files_with_topic.r#L51-L53

no longer applies to the HTML files of R 4.1.1 where it should match these two lines instead.

```
[5]:"</head><body><div class=\"container\">"
[167]:"</div></body></html>"
```

Looks like search for the line that contains or `startsWith` `</head><body>` and `endsWith` `</body></html>` should be enough.

**Comment by colettace** [comment]
For me, when I use the <code>?</code> operator or the function <code>utils::help</code> to pull the doc pages, it returns unrendered latex, rather than html.
```
library( tidyverse )
my_doc_text <- utils::help( "str_split" )
```

<img width="754" alt="Screen Shot 2021-08-17 at 3 10 14 PM" src="https://user-images.githubusercontent.com/2759698/129786397-c1213dd8-4258-4339-a57c-a49e589c2256.png">

When I try to render it using <code>IRdisplay::display_latex( my_doc_text )</code> I get an error with the following backtrace:

```
Error: No method asJSON S3 class: help_files_with_topic
Traceback:

1. IRdisplay::display_latex(my_doc_text)
2. display_raw("text/latex", FALSE, data, file)
3. publish_mimebundle(data, metadata)
4. getOption("jupyter.base_display_func")(data, metadata)
5. send_response("display_data", current_request, "iopub", list(data = data, 
 .     metadata = metadata))
6. zmq.send.multipart(socket, msg_to_wire(msg), serialize = FALSE)
7. msg_to_wire(msg)
8. charToRaw(toJSON(msg$content, auto_unbox = TRUE))
9. toJSON(msg$content, auto_unbox = TRUE)
10. asJSON(x, dataframe = dataframe, Date = Date, POSIXt = POSIXt, 
  .     factor = factor, complex = complex, raw = raw, matrix = matrix, 
  .     auto_unbox = auto_unbox, digits = digits, na = na, null = null, 
  .     force = force, indent = indent, ...)
11. asJSON(x, dataframe = dataframe, Date = Date, POSIXt = POSIXt, 
  .     factor = factor, complex = complex, raw = raw, matrix = matrix, 
  .     auto_unbox = auto_unbox, digits = digits, na = na, null = null, 
  .     force = force, indent = indent, ...)
12. .local(x, ...)
13. vapply(x, asJSON, character(1), na = na, auto_unbox = auto_unbox, 
  .     indent = indent + 2L, no_dots = no_dots, ...)
14. FUN(X[[i]], ...)
15. FUN(X[[i]], ...)
16. .local(x, ...)
17. vapply(x, asJSON, character(1), na = na, auto_unbox = auto_unbox, 
  .     indent = indent + 2L, no_dots = no_dots, ...)
18. FUN(X[[i]], ...)
19. FUN(X[[i]], ...)
20. .local(x, ...)
21. stop("No method asJSON S3 class: ", class(x))
22. base::stop(..., call. = FALSE)
```

**Comment by rvalieris** [comment]
same issue here, I can confirm that the proposed PR https://github.com/IRkernel/repr/pull/144 fixes the issue.

**Comment by kaufmanno** [comment]
I still getting the same issue under R4.1.2 in Jupyterlab 3.2.2.

**Comment by CholoTook** [comment]
Why closed?

**Comment by flying-sheep** [comment]
See the close event:

[![grafik](https://user-images.githubusercontent.com/291575/141779825-153f88c7-5513-4aba-9cf4-1e1450547964.png)](https://github.com/IRkernel/repr/pull/144)

There’s a link you can click which tells you what the fix was.
