### ISSUE TITLE
complex number in a list displayed as NULL

### ISSUE THREAD

**Issue by dennisobrien** [IRkernel/repr#15]
In the Jupyter notebook, complex numbers in a list are displayed as NULL.

    list(1+1i)
    1. NULL

But if I print it explicitly the value is displayed.

    print(1+1i)
    [[1]]
    [1] 1+1i

Other object types display correctly.  Complex numbers are the only issue I've seen.

I looked around IRkernel and IRdisplay, but I believe that this is likely the project responsible for representing R objects for display in the Jupyter notebook.  If I'm wrong, please point me to the correct project.

My system information:
- R 3.2.2 on Ubuntu 15.04
- IRkernel 0.4
- IRdisplay 0.3
- repr 0.3
- Jupyter 4.0.4

Let me know if there is any more information I can provide or debugging I should try.

**Comment by flying-sheep** [comment]
thanks!
