### ISSUE TITLE
Error printing data frame

### ISSUE THREAD

**Issue by mndrake** [IRkernel/repr#16]
Still trying to understand the dependencies or IRkernel, per @flying-sheep I'm getting a `repr` error.

I am getting a warning when printing a data frame that has more rows than are displayed when one of the columns is a factor column.

Here is an example notebook that does not render correctly for me.

In a prior version of IRkernel (0.3) it did render correctly, but the current version from github does not.

https://gist.github.com/mndrake/71ce9b15543cfa2fea46

**Comment by flying-sheep** [comment]
the error happens [here](https://github.com/IRkernel/repr/blob/1db11196858af9aff86100922561ed253ade4a7e/R/repr_matrix_df.r#L26-L49)

what it tries to do is basically inserting a new string into a factor. factors are simply integer vectors with a `levels` attribute, a small string vector corresponding to the numbers in the factor.

```r
f <- c(1L, 2L,2L, 1L)
attr(f, 'levels') <- c('bar', 'foo')
class(f) <- 'factor'
stopifnot(identical(f, factor(c('bar', 'foo', 'foo', 'bar'))))
```

we can of course insert strings into it that exist (they are looked up in the levels and their number is inserted into the factor), but we’d have to change the levels to insert new strings, which R refuses to do.

---

to fix this function, we have to append `a` all ellipsis strings to the `levels` of all factor colums of `a`.
