### ISSUE TITLE
ERROR while rich displaying an object: Error in check.length(gparname)

### ISSUE THREAD

**Issue by MrClearLovez** [IRkernel/repr#161]
when I use the clustree R package plot a picture,but i get error as

![image](https://user-images.githubusercontent.com/103395438/219282926-11463e23-3d68-425a-bfb4-092d8d152fc9.png)

I try to update repr (`devtools::install_github('IRkernel/repr')`),but not work for me.

Sincerely request your help.

**Comment by flying-sheep** [comment]
Please create a [reprex](https://reprex.tidyverse.org/#usage), I’m not going to transcribe code off an image.

you can replace the last line with `repr::repr_text(p2_tree)` to make it reproduce outside of a IRkernel session.

**Comment by MrClearLovez** [comment]
Hello, I modified it according to your method, ERROR while rich displaying an object disappeared, but&nbsp;Error in check.length(gparname) Still exist







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IRkernel/repr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月16日(星期四) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IRkernel/repr] ERROR while rich displaying an object: Error in check.length(gparname) (Issue #161)





 
Please create a reprex, I’m not going to transcribe code off an image.
 
you can replace the last line with repr::repr_text(p2_tree) to make it reproduce outside of a IRkernel session.

**Comment by MrClearLovez** [comment]
library(clustree)
***@***.***, prefix = "RNA_snn_res.")
repr::repr_text(p2_tree)











Error in check.length(gparname): 'gpar' element 'lwd' must not be length 0 Traceback: 1. repr::repr_text(p2_tree) 2. repr_text.default(p2_tree) 3. paste(capture.output(print(obj)), collapse = "\n") 4. capture.output(print(obj)) 5. withVisible(...elt(i)) 6. print(obj) 7. print.ggplot(obj) 8. ggplot_gtable(data) 9. ggplot_gtable.ggplot_built(data) 10. build_guides(plot$scales, plot$layers, plot$mapping, position,    .     theme, plot$guides, plot$labels) 11. guides_gengrob(gdefs, theme) 12. lapply(gdefs, guide_gengrob, theme) 13. FUN(X[[i]], ...) 14. guide_gengrob.colorbar(X[[i]], ...) 15. segmentsGrob(x0 = x0, y0 = y0, x1 = x1, y1 = y1, default.units = "cm",    .     gp = gpar(col = guide$ticks.colour, lwd = guide$ticks.linewidth *    .         .pt, lineend = "butt")) 16. grob(x0 = x0, y0 = y0, x1 = x1, y1 = y1, arrow = arrow, name = name,    .     gp = gp, vp = vp, cl = "segments") 17. gpar(col = guide$ticks.colour, lwd = guide$ticks.linewidth *    .     .pt, lineend = "butt") 18. validGP(list(...)) 19. numnotnull("lwd") 20. check.length(gparname) 21. stop(gettextf("'gpar' element '%s' must not be length 0", gparname),    .     domain = NA)










This is the code and the error.



Sincerely thank you for your help!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IRkernel/repr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月16日(星期四) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IRkernel/repr] ERROR while rich displaying an object: Error in check.length(gparname) (Issue #161)





 
Please create a reprex, I’m not going to transcribe code off an image.
 
you can replace the last line with repr::repr_text(p2_tree) to make it reproduce outside of a IRkernel session.

**Comment by flying-sheep** [comment]
Your email program ate some of that.

Please install and use [reprex](https://reprex.tidyverse.org/#usage) to make a reproducer

**Comment by flying-sheep** [comment]
I can’t help you unless you give me a reprex. I don’t know which data you used and so on. You need to use toy data in your example for me to be able to reproduce this.

**Comment by MrClearLovez** [comment]
Sorry for my late reply,
I have solved the problem,it is clustree's problem.






Thanks again for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IRkernel/repr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 晚上7:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IRkernel/repr] ERROR while rich displaying an object: Error in check.length(gparname) (Issue #161)





 
I can’t help you unless you give me a reprex. I don’t know which data you used and so on. You need to use toy data in your example for me to be able to reproduce this.

**Comment by flying-sheep** [comment]
OK, good to know!
