### ISSUE TITLE
change default output for R kernel to look like print() ?

### ISSUE THREAD

**Issue by david-alderson** [IRkernel/repr#165]
I do a lot of teaching for Python in Jupyter and am trying to get my colleagues to teach R using Jupyter.  (Note: I am Python guy, not an R user).

One of my colleagues is very bothered by Jupyter's default output format for a simple R vector (which is think comes from display() or a repr-like function) and difference with output from explicit print().  He wants to see print()-like output all the time, without having to explicitly type print().  He thinks Jupyter is inadequate as a teaching tool as a result.  See the example:

![Unknown](https://user-images.githubusercontent.com/62573320/233213920-1d5da8e8-2cfd-47d7-a1db-85280d880427.png)

Is there a way to change the default output in Jupyter when working with R, so the default display behavior looks like print()?

Sorry if this the wrong place to post, I couldn't find any other online forum that seemed knowledgable.  Thank you!

**Comment by flying-sheep** [comment]
Sure, see [`jupyter.display_mimetypes`](https://irkernel.github.io/docs/IRdisplay/0.4.4/IRdisplay-options.html)

I think you need to get rid of the `text/html` and maybe also the `text/markdown` mimetype from the [defaults](https://github.com/IRkernel/IRdisplay/blob/d889a75564379ab65372cb2dac92f3b356655236/R/options.r#L28-L46):

```r
options(
  jupyter.display_mimetypes = getOption('jupyter.display_mimetypes')
  |> setdiff(c('text/html'))
)
```
