### ISSUE TITLE
Limits in the number of rows displayed in data frames

### ISSUE THREAD

**Issue by rsmith31415** [IRkernel/repr#17]
There are some differences between the text/html and text/plain representations when trying to limit the number of rows in a data frame. For example, after executing the following code in the IRkernel:

    kc.execute('df <- data.frame(x=1:500, y=1:500); df[200:350,,drop=FALSE]')

The text/plain representation displays the complete data frame:

```
text/plain': u'      x   y\n200 200 200\n201 201 201\n202 202 202\n203 203 203\n204 204 204\n205 205 205\n206 206 206\n207 207 207\n208 208 208\n209 209 209\n210 210 210\n211 211 211\n212 212 212\n213 213 213\n214 214 214\n215 215 215\n216 216 216\n217 217 217\n218 218 218\n219 219 219\n220 220 220\n221 221 221\n222 222 222\n223 223 223\n224 224 224\n225 225 225\n226 226 226\n227 227 227\n228 228 228\n229 229 229\n230 230 230\n231 231 231\n232 232 232\n233 233 233\n234 234 234\n235 235 235\n236 236 236\n237 237 237\n238 238 238\n239 239 239\n240 240 240\n241 241 241\n242 242 242\n243 243 243\n244 244 244\n245 245 245\n246 246 246\n247 247 247\n248 248 248\n249 249 249\n250 250 250\n251 251 251\n252 252 252\n253 253 253\n254 254 254\n255 255 255\n256 256 256\n257 257 257\n258 258 258\n259 259 259\n260 260 260\n261 261 261\n262 262 262\n263 263 263\n264 264 264\n265 265 265\n266 266 266\n267 267 267\n268 268 268\n269 269 269\n270 270 270\n271 271 271\n272 272 272\n273 273 273\n274 274 274\n275 275 275\n276 276 276\n277 277 277\n278 278 278\n279 279 279\n280 280 280\n281 281 281\n282 282 282\n283 283 283\n284 284 284\n285 285 285\n286 286 286\n287 287 287\n288 288 288\n289 289 289\n290 290 290\n291 291 291\n292 292 292\n293 293 293\n294 294 294\n295 295 295\n296 296 296\n297 297 297\n298 298 298\n299 299 299\n300 300 300\n301 301 301\n302 302 302\n303 303 303\n304 304 304\n305 305 305\n306 306 306\n307 307 307\n308 308 308\n309 309 309\n310 310 310\n311 311 311\n312 312 312\n313 313 313\n314 314 314\n315 315 315\n316 316 316\n317 317 317\n318 318 318\n319 319 319\n320 320 320\n321 321 321\n322 322 322\n323 323 323\n324 324 324\n325 325 325\n326 326 326\n327 327 327\n328 328 328\n329 329 329\n330 330 330\n331 331 331\n332 332 332\n333 333 333\n334 334 334\n335 335 335\n336 336 336\n337 337 337\n338 338 338\n339 339 339\n340 340 340\n341 341 341\n342 342 342\n343 343 343\n344 344 344\n345 345 345\n346 346 346\n347 347 347\n348 348 348\n349 349 349\n350 350 350'}
```

However, the text/html representation limits the data frame and for some reason, includes an incorrect number in the `th` element (`<th scope=row>31</th><td>\u22ee</td><td>\u22ee</td>`).

```
'text/html': u'<table>\n<thead><tr><th></th><th scope=col>x</th><th scope=col>y</th></tr></thead>\n<tbody>\n\t<tr><th scope=row>200</th><td>200</td><td>200</td></tr>\n\t<tr><th scope=row>201</th><td>201</td><td>201</td></tr>\n\t<tr><th scope=row>202</th><td>202</td><td>202</td></tr>\n\t<tr><th scope=row>203</th><td>203</td><td>203</td></tr>\n\t<tr><th scope=row>204</th><td>204</td><td>204</td></tr>\n\t<tr><th scope=row>205</th><td>205</td><td>205</td></tr>\n\t<tr><th scope=row>206</th><td>206</td><td>206</td></tr>\n\t<tr><th scope=row>207</th><td>207</td><td>207</td></tr>\n\t<tr><th scope=row>208</th><td>208</td><td>208</td></tr>\n\t<tr><th scope=row>209</th><td>209</td><td>209</td></tr>\n\t<tr><th scope=row>210</th><td>210</td><td>210</td></tr>\n\t<tr><th scope=row>211</th><td>211</td><td>211</td></tr>\n\t<tr><th scope=row>212</th><td>212</td><td>212</td></tr>\n\t<tr><th scope=row>213</th><td>213</td><td>213</td></tr>\n\t<tr><th scope=row>214</th><td>214</td><td>214</td></tr>\n\t<tr><th scope=row>215</th><td>215</td><td>215</td></tr>\n\t<tr><th scope=row>216</th><td>216</td><td>216</td></tr>\n\t<tr><th scope=row>217</th><td>217</td><td>217</td></tr>\n\t<tr><th scope=row>218</th><td>218</td><td>218</td></tr>\n\t<tr><th scope=row>219</th><td>219</td><td>219</td></tr>\n\t<tr><th scope=row>220</th><td>220</td><td>220</td></tr>\n\t<tr><th scope=row>221</th><td>221</td><td>221</td></tr>\n\t<tr><th scope=row>222</th><td>222</td><td>222</td></tr>\n\t<tr><th scope=row>223</th><td>223</td><td>223</td></tr>\n\t<tr><th scope=row>224</th><td>224</td><td>224</td></tr>\n\t<tr><th scope=row>225</th><td>225</td><td>225</td></tr>\n\t<tr><th scope=row>226</th><td>226</td><td>226</td></tr>\n\t<tr><th scope=row>227</th><td>227</td><td>227</td></tr>\n\t<tr><th scope=row>228</th><td>228</td><td>228</td></tr>\n\t<tr><th scope=row>229</th><td>229</td><td>229</td></tr>\n\t<tr><th scope=row>31</th><td>\u22ee</td><td>\u22ee</td></tr>\n\t<tr><th scope=row>321</th><td>321</td><td>321</td></tr>\n\t<tr><th scope=row>322</th><td>322</td><td>322</td></tr>\n\t<tr><th scope=row>323</th><td>323</td><td>323</td></tr>\n\t<tr><th scope=row>324</th><td>324</td><td>324</td></tr>\n\t<tr><th scope=row>325</th><td>325</td><td>325</td></tr>\n\t<tr><th scope=row>326</th><td>326</td><td>326</td></tr>\n\t<tr><th scope=row>327</th><td>327</td><td>327</td></tr>\n\t<tr><th scope=row>328</th><td>328</td><td>328</td></tr>\n\t<tr><th scope=row>329</th><td>329</td><td>329</td></tr>\n\t<tr><th scope=row>330</th><td>330</td><td>330</td></tr>\n\t<tr><th scope=row>331</th><td>331</td><td>331</td></tr>\n\t<tr><th scope=row>332</th><td>332</td><td>332</td></tr>\n\t<tr><th scope=row>333</th><td>333</td><td>333</td></tr>\n\t<tr><th scope=row>334</th><td>334</td><td>334</td></tr>\n\t<tr><th scope=row>335</th><td>335</td><td>335</td></tr>\n\t<tr><th scope=row>336</th><td>336</td><td>336</td></tr>\n\t<tr><th scope=row>337</th><td>337</td><td>337</td></tr>\n\t<tr><th scope=row>338</th><td>338</td><td>338</td></tr>\n\t<tr><th scope=row>339</th><td>339</td><td>339</td></tr>\n\t<tr><th scope=row>340</th><td>340</td><td>340</td></tr>\n\t<tr><th scope=row>341</th><td>341</td><td>341</td></tr>\n\t<tr><th scope=row>342</th><td>342</td><td>342</td></tr>\n\t<tr><th scope=row>343</th><td>343</td><td>343</td></tr>\n\t<tr><th scope=row>344</th><td>344</td><td>344</td></tr>\n\t<tr><th scope=row>345</th><td>345</td><td>345</td></tr>\n\t<tr><th scope=row>346</th><td>346</td><td>346</td></tr>\n\t<tr><th scope=row>347</th><td>347</td><td>347</td></tr>\n\t<tr><th scope=row>348</th><td>348</td><td>348</td></tr>\n\t<tr><th scope=row>349</th><td>349</td><td>349</td></tr>\n\t<tr><th scope=row>350</th><td>350</td><td>350</td></tr>\n</tbody>\n</table>\n'
```

I think there are 2 issues here:

1. The text/plain representation should be followed and not limiting the number of rows printed when the size of the response is reasonably small (e.g. 1000+ rows)
2. When limiting the number of rows, the element in `<th scope=row>31</th>` should also display \u22ee instead of "31".

By the way, this is also happening in the latex representation. I tested this in the development version of IRkernel.

Thanks

**Comment by rsmith31415** [comment]
Assuming I'm testing correctly the latest changes, this fixes the second issue in which the `th` element displayed 31. However, the dataframe still appears as a summary, instead of showing the full dataframe. Most of the time, after subsetting a dataframe (e.g. `df[200:260,,drop=FALSE]`), the user expects a complete representation of the data. Currently, the previous example outputs this:

![screenshot from 2015-11-17 19-32-22](https://cloud.githubusercontent.com/assets/599274/11230156/f9b2640a-8d61-11e5-9f9b-7d5035670ec3.png)

**Comment by flying-sheep** [comment]
complete representations are infeasible because other than a text console, the notebook has no scrollback buffer that can be truncated.

i therefore fixed the inconsitency by making the text repr also truncate :wink: 

use [`options(repr.matrix.max.rows = ..., repr.matrix.max.cols = ...)`](https://github.com/IRkernel/repr/blob/42b2ec756d14d551c863d09425640abc72d0b889/R/options.r#L71-L72) to adjust this

**Comment by flying-sheep** [comment]
and in case your problem is that this shows ellipses when eliding just one row – that’s an edge case that i don’t think is too important. but feel free to do a PR to fix it.

**Comment by rsmith31415** [comment]
@flying-sheep Sure, complete representations for all dataframes is not desirable but only after subsetting. If that is too complicated, I think another option is to use it for dataframes that are likely to be inspected row by row (e.g. number of rows < threshold).

`options(repr.matrix.max.rows,... ` is a good tip but I think it would be annoying to use it constantly.

Wouldn't this be solved by simply changing the default value in `options.r`:

```
condopt(
		repr.vector.quote = TRUE,
		repr.matrix.max.rows = 60,
		repr.matrix.max.cols = 20,
		repr.matrix.latex.colspec = list(row.head = 'r|', col = 'l', end = ''),
		repr.function.highlight = FALSE)
```

Currently, the number is 60. Maybe, something like 300 or 500 would be a reasonable number of rows to be displayed without causing issues with the notebook.

**Comment by flying-sheep** [comment]
i used the [default values of pandas](https://github.com/pydata/pandas/blob/12d9938a759c2c1566a7a82eb74d1e6a8535dfa9/pandas/core/config_init.py#L255-L259)

check IRkernel/IRkernel#174 for a bit of discussion.

my use case when printing a data frame is basically “did everything work? is it scaled appropriately? do the factors look OK?”, for which a less than one screen big representation is perfect.

i can’t see any patterns for hundreds of rows and use statistics instead.

**Comment by takluyver** [comment]
I'm open to tweaking the default a bit, but I think the current default of 60 rows is in about the right ballpark, and 300-500 would be too high. You're not going to be examining that many rows manually very often (or if you are, you're doing something wrong), and if you accidentally display a big dataframe, it can make scrolling quite unwieldy.

It is an option, so if you need to see data frames that big in their entirety, you can set it to what you need. But I think what we've got is a fairly sensible default.

**Comment by flying-sheep** [comment]
> Notice that my request was mainly focused to subsetting a dataframe but since that could be complicated to implement

impossible. subsetting a data frame yields another data frame. repr has no idea if that data frame comes from subsetting, a function call or simply a variable.

> I thought maybe changing the defaults would be an easier solution.

it would of course “solve” that the defaults don’t match your preferences, but since @takluyver also likes the smaller defaults more, i think we’ll leave them be :smile: 

> A couple of use cases I found recently:

of course if you want to find semantics in textual data, you do have to check everything.

but for time series analysis, there’s books and lectures on things you can do. and i don’t think “look at the raw numbers” is ever part of it :wink: 

---

i wrote the `condopt` function for the precise reason that users can set options *before* loading the package.

put `options(repr.matrix.max.rows = 2000, repr.matrix.max.cols = 1000)` into [`~/.Rprofile`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html) and you’re set

**Comment by takluyver** [comment]
I don't think the use cases for looking at individual rows are very compelling. By the time you have ~100 data points to understand, you're almost certainly going to understand them better by finding a way to summarise, visualise or process them than by looking at the raw data in a table.

Matching them to another data source is the most convincing example, but if you really needed to do that by hand, I think you'd load the data in a spreadsheet so you could easily record the connections you were making from the data.

There are bound to be occasions when you'd want to look through the whole of a 200-row data frame in a notebook, but I think they're the exception, not the rule. And I'm quite happy for the interface to give people a little extra push away from that, and towards finding a smarter way to look at what they're interested in.

**Comment by rsmith31415** [comment]
@flying-sheep It is certainly a matter of preference. On the other side of the spectrum, I could easily expect that people accustomed to analyze bigger data sets 300 or 500 rows wouldn't be good enough for them. 

>but for time series analysis, there’s books and lectures on things you can do. and i don’t think “look at the raw numbers” is ever part of it

That's because books and lectures teach the concepts and general ideas, not real world usage. You're going to need to look at the rows because data is messy and sometimes, a boxplot is not going to be enough.

> put options(repr.matrix.max.rows = 2000, repr.matrix.max.cols = 1000) into ~/.Rprofile and you’re set

Sure. Thanks.

@takluyver Sometimes you can summarize but not always (as @flying-sheep said, textual data need to be analyzed manually) Remember, I'm talking about the situation in which you already extracted a subset of the data set. Maybe you need to inspect 200+ rows looking for something suspicious. It is faster and more accurate to do that manually than trying several graphical approaches or even worst, graphical approaches may not be applicable in the first place.

I think you're trying to make an unnecessary argument, that if you have 100+ rows, you're better off trying to use summaries or graphics. Obviously, this begs the question, why 100+? But why not 200 rows or 500 rows? Of course, there is not something inherent in 100 to make it more appropriate. There will be some situations which require 500 rows and others 50 rows, but I wouldn't argue about what is adequate without looking at the data beforehand. A better argument (or explanation) is the one made by @flying-sheep; pandas uses 60 rows and that has worked well so far.

**Comment by JanSchulz** [comment]
Thanks for this fix, I just ran into it as well (800mb csv 1000+ columns and rows) file which was blown up to multiple GB rsession... had to kill the kernel to get a back into business... :-)

**Comment by flying-sheep** [comment]
hmm, you had because you didn’t install this version yet?

**Comment by JanSchulz** [comment]
@flying-sheep yes :-) Running releases in my notebook R kernel...

**Comment by flying-sheep** [comment]
pff, releases! as a contributor you’re morally obliged to run git master :stuck_out_tongue_winking_eye:
