### ISSUE TITLE
Error in namespaceExport(ns, exports) : undefined exports: repr.format

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [IRkernel/repr#2]
Trying to install this on R 3.1.3., but with very little success. I get as below:

```
> library(devtools); install_github('IRkernel/repr'); install_github('armstrtw/rzmq'); install_github('IRkernel/IRdisplay'); install_github('IRkernel/IRkernel'); IRkernel::installspec()
Downloading github repo IRkernel/repr@master
Installing repr
'/usr/lib/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/Rtmp14FsOJ/devtools62f9733cb/IRkernel-repr-7b22bc2'  \
  --library='/usr/local/lib/R/site-library' --install-tests

* installing *source* package ‘repr’ ...
** R
** preparing package for lazy loading
** help
No man pages found in package  ‘repr’
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: S3 methods ‘repr_html.repr’, ‘repr_javascript.repr’, ‘repr_jpg.repr’, ‘repr_json.repr’, ‘repr_latex.repr’, ‘repr_markdown.repr’, ‘repr_pdf.repr’, ‘repr_png.repr’, ‘repr_svg.repr’, ‘repr_text.repr’ were declared in NAMESPACE but not found
Error in namespaceExport(ns, exports) : undefined exports: repr.format
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/repr’
Error: Command failed (1)
```

I'm on an Ubuntu Docker container based on jupyter/jupyterhub. This is a relatively recent error - I haven't come across it before.

**Comment by bnmtthws** [comment]
seeing the same here, on Mac OSX 10.10.3 with R 3.1.3

**Comment by takluyver** [comment]
Sorry about that, try again now.

**Comment by chrisvoncsefalvay** [comment]
OK now although still raising error:

```
>
S3 methods ‘repr_html.repr’, ‘repr_javascript.repr’, ‘repr_jpg.repr’, ‘repr_json.repr’, ‘repr_latex.repr’, ‘repr_markdown.repr’, ‘repr_pdf.repr’, ‘repr_png.repr’, ‘repr_svg.repr’, ‘repr_text.repr’ were declared in NAMESPACE but not found
```

**Comment by takluyver** [comment]
Thanks, that too should be fixed now.

**Comment by flying-sheep** [comment]
why doesn’t RStudio remove things from NAMESPACE? do i really have to delete NAMESPACE and force it to recreate it if i want to be sure my changes didn’t break something?

very sorry, i should be less sloppy :disappointed_relieved:

**Comment by takluyver** [comment]
I don't know - it seems like it should do that better, but I'm not using
Rstudio, so I don't know how to make it do so.

**Comment by flying-sheep** [comment]
you should start using it, it’s very convenient :smiley: 

and it seems to do it. no idea why it didn’t then!

**Comment by MichielStock** [comment]
I have the same problem installing IRdisplay...

> install_github("IRkernel/IRdisplay")
Downloading github repo IRkernel/IRdisplay@master
Installing IRdisplay
Installing dependencies for IRdisplay:
repr
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/47/tqsl_skx6ml299bcyhpslmr80000gn/T/Rtmpp4DfPZ/devtools490b76e3244c/IRkernel-IRdisplay-7b2765c'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

ERROR: dependency ‘repr’ is not available for package ‘IRdisplay’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/IRdisplay’
Error: Command failed (1)
In addition: Warning message:
package ‘repr’ is not available (for R version 3.2.0) 
> 


My NAMESPACE does not contain the repr.format that they recommend to remove...
Any help?

**Comment by JanSchulz** [comment]
@MichielStock Do you have the package `repr` installed? install_github does not resolve dependencies, so you must work yourself up from repr -> irdisplay -> irkernel. Or simple use the packages at irkernel.gihub.io.

**Comment by MichielStock** [comment]
ok, installing from irkernel.gihub.io seems to have done the trick. I can now open a R notebook, thank a lot!

**Comment by michaelpacer** [comment]
I think both of you actually meant irkernel.github.io given that gihub seems to not exist. It'll probably help a lot of people who are new to this sort of thing if your link works without manual editing (e.g., if they got here via a google search and didn't notice that github is the name of the site they are reading this on).

**Comment by kanny789** [comment]
Hi Guys I am trying to install paRdot using devtools::install_github("demgenman/paRdot"). I get the below error
Error: package or namespace load failed for 'paRdot' in namespaceExport(ns, exports):
 undefined exports: set_curl_options
Error: loading failed
Execution halted

Any help is appereciated

**Comment by englianhu** [comment]
> Trying to install this on R 3.1.3., but with very little success. I get as below:
> 
> ```
> > library(devtools); install_github('IRkernel/repr'); install_github('armstrtw/rzmq'); install_github('IRkernel/IRdisplay'); install_github('IRkernel/IRkernel'); IRkernel::installspec()
> Downloading github repo IRkernel/repr@master
> Installing repr
> '/usr/lib/R/bin/R' --vanilla CMD INSTALL  \
>   '/tmp/Rtmp14FsOJ/devtools62f9733cb/IRkernel-repr-7b22bc2'  \
>   --library='/usr/local/lib/R/site-library' --install-tests
> 
> * installing *source* package ‘repr’ ...
> ** R
> ** preparing package for lazy loading
> ** help
> No man pages found in package  ‘repr’
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> Warning: S3 methods ‘repr_html.repr’, ‘repr_javascript.repr’, ‘repr_jpg.repr’, ‘repr_json.repr’, ‘repr_latex.repr’, ‘repr_markdown.repr’, ‘repr_pdf.repr’, ‘repr_png.repr’, ‘repr_svg.repr’, ‘repr_text.repr’ were declared in NAMESPACE but not found
> Error in namespaceExport(ns, exports) : undefined exports: repr.format
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing ‘/usr/local/lib/R/site-library/repr’
> Error: Command failed (1)
> ```
> 
> I'm on an Ubuntu Docker container based on jupyter/jupyterhub. This is a relatively recent error - I haven't come across it before.

installed upon https://github.com/edgexfoundry/edgex-go/issues/22#issuecomment-370032619

**Comment by flying-sheep** [comment]
The line `'/tmp/Rtmp14FsOJ/devtools62f9733cb/IRkernel-repr-7b22bc2'` implies that you somehow ended up with commit 7b22bc2 from 2015.

That’s either some remaining temporary file or some bug in devtools/remotes. Current repr master doesn’t have that undefined export anymore since 7b698c0
