### ISSUE TITLE
Markdown support for data.table.

### ISSUE THREAD

**Issue by karldw** [IRkernel/repr#24]
It would be nice if there was a markdown representation of data.tables.  For instance, this command returns NULL: `repr_markdown(iris)`.
On the other hand, this command works, but the table isn't great: `repr_markdown(as.matrix(iris))`.

Among other things, the lack of markdown conversion for data.tables creates mysterious errors when a data.frame is included in a list.

``` R
repr_markdown(list(a=1, b=iris))
Error in vapply(seq_along(mapped), function(i) { : 
  values must be length 1,
 but FUN(X[[2]]) result is length 0
```

(Because there's no data.frame converter for markdown, an attempt to call repr_markdown returns NULL, which has length 0.)

Since markdown knows about HTML, could would it be possible to just use the HTML functions?

**Comment by flying-sheep** [comment]
hmm, good point. i’d rather introduce a `repr_fallback_*` which would be used in recursive datastructures if there’s no dedicated repr for that format.

it would probably call `repr_text_*` for most, and escape the text for LaTeX and HTML. maybe fallback to rendering a text repr to an image in the case of PNG, SVG, …?

**Comment by karldw** [comment]
Closing because this seems to have been solved sometime in the last three years

**Comment by flying-sheep** [comment]
haha thank you!
