### ISSUE TITLE
?rename will print the help as an output, not a page

### ISSUE THREAD

**Issue by janschulz** [IRkernel/repr#26]
Executing `?rename` (dplr package) will output the help text into the output area. IMO it should go into a page much like `str?`, which will display a help page in an python kernel.

**Comment by takluyver** [comment]
I could go either way on it.

**Comment by JanSchulz** [comment]
The page has the advantage that I can scroll that independently (at least when opened in a new tab) but to see something in the output place, you have to scroll down, find the thing you needed and then scroll up again to change the cell...

**Comment by JanSchulz** [comment]
I also wouldn't mind a sidebar like here: https://github.com/minrk/nbextension-scratchpad

**Comment by flying-sheep** [comment]
i opted to do that because the pager still can’t use mime bundles, and HTML help is better than ASCII help.

**Comment by takluyver** [comment]
As of 4.0 the pager can display HTML: jupyter/notebook#196

That issue (now migrated to jupyter/notebook#1135) is still open for using the full display machinery so you could send e.g. an image to the pager. But if we want to display HTML help in the pager, that's already possible.

**Comment by flying-sheep** [comment]
oh nice! in this case, the kernel should have an option for selecting pager vs. inline.

i like the inline variant (+ eventually a hotkey to get the pager display context help)

**Comment by takluyver** [comment]
For reference, there's an equivalent option in IPython, called `display_page`:

> Default: False
> If True, anything that would be passed to the pager will be displayed as regular output instead.

**Comment by JanSchulz** [comment]
Do we already have a way to specify options? An easy way would be to use env variables which can be set via the kernel spec file...

And pretty please, for the sake of my little mouse which today had to make several more scroll rounds: please change to use the pager :-)

**Comment by takluyver** [comment]
We have various settings in the R options mechanism, and I think that's where this should go too:
https://github.com/IRkernel/IRkernel/blob/master/R/options.r

Let's go for putting help content in the pager by default, and users who want it as inline content can set the option. That's in parallel with the option in IPython.

**Comment by JanSchulz** [comment]
ah, ok, options inside the execution environment.

**Comment by flying-sheep** [comment]
> Let's go for putting help content in the pager by default, and users who want it as inline content can set the option. That's in parallel with the option in IPython.

good!

**Comment by flying-sheep** [comment]
fixed in IRkernel/IRkernel@3ff41c733aaba801823217135e5371fc934292eb

**Comment by flying-sheep** [comment]
@takluyver but there’s a problem: sending a mime bundle with HTML content shows nothing:

![spectacle b29029](https://cloud.githubusercontent.com/assets/291575/14404680/c5674d6e-fe7c-11e5-83ae-2bc26d951f99.png)

**Comment by flying-sheep** [comment]
aw yiss, now it works. and it looks gorgeous!

> ![spectacle s30135](https://cloud.githubusercontent.com/assets/291575/14744008/ff85d6c8-08a4-11e6-89b4-b2d7a854d065.png)

**Comment by takluyver** [comment]
:cake: :sparkles: 

What did you have to do to get it working?

**Comment by flying-sheep** [comment]
probably IRkernel/IRkernel@26dc7bcb03cb50c5fb2e951c21a17e5ec93ede44
