### ISSUE TITLE
png plots do not have a background color

### ISSUE THREAD

**Issue by janschulz** [IRkernel/repr#29]
The following code cell prints the background color as "white", but when I save the plot and then open the plot in a fileviewer (or you might fiddle with background color of the notebook), the plot has a transparent background color.
```
options(jupyter.plot_mimetypes = c("text/plain", "image/png" )) # no more svg...
getOption('repr.plot.bg') # prints "white"
library("ggplot2")
data <- data.frame(x=c(1,2), y=c(3,4))
ggplot(data, aes(x=x, y=y)) + geom_point() + theme_minimal() # transparent background :-(
```

**Comment by flying-sheep** [comment]
good.
