### ISSUE TITLE
support pander

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/repr#33]
pander returns markdown (and is used extensively with knitr to display rich tables), this should be displayed as markdown to be rendered in the notebook:
```
df <- data.frame(a=1:8, b=factor(c(0,1,0,1,0,1,0,1), levels=c(0,1), labels=c("a", "b")) )
pander(df %>% t.test(a~b, data = .) %>% tidy())
```

**Comment by JanSchulz** [comment]
[From the problems I run into, I get the feeling that I'm the first to actually use irkernel to do data analysis with the current hadleyverse stack:-/]

**Comment by JanSchulz** [comment]
Ok, this looks like something which is not so nice:

```
df <- data.frame(a=1:8, b=factor(c(0,1,0,1,0,1,0,1), levels=c(0,1), labels=c("a", "b")) )
t <- pander(df %>% t.test(a~b, data = .) %>% tidy()) # prints the markdown
str(t) # NULL
```

shows that t does not get anything assigned :-( Looks like this isn't easily changed without a change in pander itself :-( E.g. it would be easier if pander would return a object and have a default print method for that object and we could then add a `repr_markdown.pander_object` method.

CC: @Rapporter

```
function (x = NULL, ...) 
{
    kaao <- panderOptions("knitr.auto.asis")
    if (isTRUE(panderOptions("knitr.auto.asis")) && isTRUE(getOption("knitr.in.progress")) && 
        requireNamespace("knitr", quietly = TRUE)) {
        panderOptions("knitr.auto.asis", FALSE)
        stdout <- vector("character")
        con <- textConnection("stdout", "wr", local = TRUE)
        sink(con)
        sink(con, type = "message")
        on.exit({
            if (panderOptions("knitr.auto.asis") != kaao) {
                panderOptions("knitr.auto.asis", kaao)
            }
            sink()
            sink(type = "message")
            close(con)
            if (tail(stdout, 1) == "") {
                stdout <- c(stdout, "")
            }
            return(knitr::asis_output(paste(stdout, collapse = "\n")))
        })
    }
    UseMethod("pander", x)
}
```

**Comment by JanSchulz** [comment]
And the workaround also doesn't work:

```
df <- data.frame(a=1:8, b=factor(c(0,1,0,1,0,1,0,1), levels=c(0,1), labels=c("a", "b")) )
#print(df %>% t.test(a~b, data = .))
#print(df %>% t.test(a~b, data = .) %>% tidy())
t <- pander_return(df %>% t.test(a~b, data = .) %>% tidy())
display_markdown(cat(t, sep="\n"))
```

```
[... markdown table as text plain ...]

Error in prepare_content(isbinary, data, file): Either need to specify data or file, but not both
Traceback:

1. display_markdown(cat(t, sep = "\n"))
2. display_raw("text/markdown", FALSE, data, file)
3. prepare_content(isbinary, data, file)
4. stop("Either need to specify data or file, but not both")
```

**Comment by flying-sheep** [comment]
i don’t think there’s a possibility to do single table cells in markdown.

**Comment by JanSchulz** [comment]
I think the problem already starts above: 

```
-------------------------------------------------------------------------------
estimate   estimate1   estimate2   statistic   p.value   parameter   conf.low 
---------- ----------- ----------- ----------- --------- ----------- ----------
-1          4           5        -0.5477    0.6036        6        -5.467  
-------------------------------------------------------------------------------

Table: Table continues below

-----------
conf.high 
-----------
3.467   
-----------
```

In this case, even the first headline is not displayed as headline :-(

**Comment by JanSchulz** [comment]
So, to summarize, supporting `pander` out of the box doesn't work because:

* pander prints markdown to stdout (=displayed in the notebook as "text/plain") so we would have to replace the pander function with our own function to use the display system instead or upstream a patch which would reverse the pander logic (`pander = cat the MD to stdout-> sink stdout to a string -> return string` vs `pander_new = return object -> print object`) or at leats do something similar to the knitr workaround (which returns a asis object when an option is set and the it detects a knitr run) to hook in our own `repr_markdown.pander_object`.
* the resulting markdown is incompatible with the markdown display library in the jupyter notebook because it doesn't understand the table format

Bummer :-(

**Comment by JanSchulz** [comment]
Damn:

> stargazer uses cat() to output LaTeX/HTML code or ASCII text for the table.

**Comment by flying-sheep** [comment]
why? [`capture.output`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/capture.output.html) is our friend!

**Comment by JanSchulz** [comment]
... but this needs special treatment in the form of a wrapper function and therefore the nice examples (e.g. `pander(models...)` do not work :-( I think it would be really nice if we could go and advertise a better patter for this (e.g. return an object and include a print function for that object; maybe talk to the knitr people to unify the repr/knitr asis functionality).

[I also find using capture.output slightly revolting:  :-(]

Anyway: the more depressing aspect here is that the notebook doesn't understand the markdown table syntax and therefore it seems it can't produce nicely formatted tables :-( I haven't yet found a way to convert the markdown to html via pandoc (e.g. knitr includes a `pandoc`function, but it requires tempfiles :-() 

@takluyver Do you think there is a chance to get a better markdown library in the notebook?

**Comment by flying-sheep** [comment]
> I also find using capture.output slightly revolting: :-(

sure, but we gotta use what we have.

**Comment by takluyver** [comment]
The [current CommonMark spec](http://spec.commonmark.org/0.24/) does not describe any Markdown table syntax, and we'd broadly like to stick to that standard.

**Comment by JanSchulz** [comment]
I can understand the "sticking to standards" argument, but I think this will become a problem for the adoption of the R kernel/notebook in the R world: pandoc is the defacto standard of markdown in knitr and IMO the notebook is competing with knitr. Not having nice summary tables (in both html and the PDF generated by nbconvert) is IMO a bad signal if one want's to use the notebook together with statistical research.  :-( Lets hope that this is fixed in the commonmark spec in the near future...

On a sidenote: having nicer tables in general would be nice... Bootstrap has nice table styles, maybe adding that to the notebook would already by a nice thing...

**Comment by JanSchulz** [comment]
Here is my current version of a pander based table generation:

```
df <- data.frame(a=1:8, b=factor(c(0,1,0,1,0,1,0,1), levels=c(0,1), labels=c("a", "b")) )
nice_pander <- function(...){
    t = capture.output(pander(...))
    mdFile <- tempfile(fileext=".md")
    cat(paste(t, collapse="\n"), file=mdFile)
    htmlFile <- knitr::pandoc(input = mdFile, format = "html")
    t = readr::read_file(htmlFile)
    #print(t)
    display_html(paste(t, collapse="\n"))
    display_html("<link rel='stylesheet' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'>
<script src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'></script>
<script>$('tr.header').parent('thead').parent('table').addClass('table table-condensed');</script>
")
}
nice_pander(df %>% t.test(a~b, data = .) %>% tidy())
```

It currently doesn't work: it seems the classes get assigned to new appended table, but there is no styling. Not sure why that is, could be a different `.table` css rule in the default notebook css...

**Comment by JanSchulz** [comment]
The last is now https://github.com/jupyter/notebook/issues/1182

**Comment by daroczig** [comment]
I've just found this thread thanks to Google Alerts :) I am the maintainer of the `pander` package, and happy to help you fine-tine the output for your needs -- just please let me know what's the optimal output.

Eg if you need another markdown table format instead of the default `multiline`, you could set a global option as `panderOptions('table.style', 'grid')` for the Emacs-like grid format, which will be used in all future `pander` calls, or eg `rmarkdown` for the PHP Extra markdown version. To disable splitting the tables, you could do `panderOptions('table.split.table', Inf)`

Please let me know if I can help/contribute with something here.

Best,
Gergely

PS: thanks for the @Rapporter above, but this did not trigger any mail to me or the other collaborators :( Please feel free to ping my handle directly.

**Comment by flying-sheep** [comment]
@daroczig you went through `cat` instead of “return a class with a `print` method defined”. is it possible to change this?

**Comment by daroczig** [comment]
Not sure if I understand the question, but if you would require `pander` to return an object -- that's against the original intention of the method, as `pander` was designed to write to `stdout`. There's `pander_return`, which is just a wrapper around `capture.output` BTW, and you could `paste` the returned character vector separated by `\n` -- just like @JanSchulz suggested.

But as I already changed that behavior for more seamless integration within `knitr`, this could be done for `IRkernel` as well, I suppose. The pimpliest thing could be you setting the `knitr.in.progress` option, just like `knitr` does, or let me know how I can identify if `pander` is being called inside of `IRkernel`.

**Comment by JanSchulz** [comment]
@daroczig:

> as pander was designed to write to stdout

This would happen as well, just not during the pander call but during a new `print.pander(...)` which R does automatically when it encounters an object. For the integration with knitr, you would supply a `knit_print.pander` function, which would return an `knit_asis` object (no need to have the special cases in the pander call anymore).

RE knitr and its current `knit_asis` object: we could use that by building `repr_*.knit_asis` methods, but this would need an indicator what the `knit_asis` object holds (e.g. markdown, html, latex,...), but as far as I see there is none :-(. The problem here is that during a knitr run, the methods know what the final output is and therefore decide what to put into the `knit_asis` object. In the jupyter kernel, we produce all output which we can get for an object and so would also call `repr_html.knit_asis(panders_asis_object)` which would result in markdown output in the place where only html should be :-( .

The knitr way has the advantage, that the `knit_asis` object can also hold meta things like css for the html content or the package loading in latex, which knitr would only include once. We currently need to do inline styling on every object we `repr`... :-(

@flying-sheep @takluyver I think we should produce a vignette together with the knitr people how to best build something which works in both worlds.

E.g. 
* return an object with a unique class, e.g. `your_object`
* build three methods: `print.your_object()` (which `cat`s to stdout), `knit_print.your_object()` (which returns a asis object for the current knitr output context), and `repr_xxx.your_object()` (for all output types you support, output as a string). You can probably reuse the `repr_xxx.your_object()` in the `knit_print.your_object()` one.
* register the three methods with the system which does the dispatch (e.g. `print(your_object)` dispatches to `print.your_object(your_object)`) [Or is simply calling your method the right way enough?]

**Comment by JanSchulz** [comment]
Actually there such an vignette: https://github.com/yihui/knitr/blob/master/vignettes/knit_print.Rmd, but it just covers the knit_print part...

**Comment by flying-sheep** [comment]
> we could use that by building `repr_*.knit_asis` methods, but this would need an indicator what the `knit_asis` object holds (e.g. markdown, html, latex,...), but as far as I see there is none

this is the reason i build repr. because i thought the “asis” approach to be fundamentally flawed. the idea was that knitr switches to use `repr` under the hood.

**Comment by JanSchulz** [comment]
I think the python code already has such a way: https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L81

```
def publish_display_data(data, metadata=None, source=None):
    """Publish data and metadata to all frontends.
    See the ``display_data`` message in the messaging documentation for
    more details about this message type.
    The following MIME types are currently implemented:
    * text/plain
    * text/html
    * text/markdown
    * text/latex
    * application/json
    * application/javascript
    * image/png
    * image/jpeg
    * image/svg+xml
    Parameters
    ----------
    data : dict
        A dictionary having keys that are valid MIME types (like
        'text/plain' or 'image/svg+xml') and values that are the data for
        that MIME type. The data itself must be a JSON'able data
        structure. Minimally all data should have the 'text/plain' data,
        which can be displayed by all frontends. If more than the plain
        text is given, it is up to the frontend to decide which
        representation to use.
    metadata : dict
        A dictionary for metadata related to the data. This can contain
        arbitrary key, value pairs that frontends can use to interpret
        the data. mime-type keys matching those in data can be used
        to specify metadata about particular representations.
    source : str, deprecated
        Unused.
        """
```

If we want integration with knitr, what can we give them? The problem is that current contract for the `repr` methods say, that they return strings. So if we want that `knit_print.default()` ([source](https://github.com/yihui/knitr/blob/ec88e40b2d4e14078d30ded688f6daad4ba5b4d2/R/output.R#L619-L631)) becomes a wrapper around repr, we need to change that and do it fast before someone (aka pander :-)) starts implementing its interface.

```r
knit_print.default(...){
   # get current output context
   # call the proper repr_<output>(...), wrap it in a knit_asis object
   # if NULL, try use the old content of the default method
}
``` 

But for this to work, we would also need to remove most of our methods, e.g. for vector and so on, because otherwise that becomes a big regression on knitrs side (or knitr needs methods for these objects too, which just call `normal_print()`)...

Whatever we do, we should probably open a bugreport on the knitr side with this idea...

**Comment by JanSchulz** [comment]
An idea for the new repr interface could be to return an object/tuple with three properties `(content, metadata, "type")`. The display methods could then combine content with metadata to get the proper content to send over the wire until the notebook supports metadata (does it? Haven't seen a spec what metadata is used in the frontend. Maybe @takluyver knows more?)

**Comment by flying-sheep** [comment]
tuple? we’re in R.

and we can simply add attributes to the object returned, which avoids changing signatures.

an example where i loop a bunch of things, create their HTML reprs and only do setup once:

```r
repr_html.stuff <- function(x, ...) {
    ...
    structure(html_markup, setup = list(stuff_setup_script = '<script>...</script>')
}

html_setups_seen <- character()
for (thing in things) {
    thing_repr <- repr_html(thing)
    thing_setups <- attr(thing_repr, 'setup')
    new_setups <- stuff_setups[intersect(html_setups_seen, names(thing_setups))]
    html_setups_seen <- c(html_setups_seen, names(new_setups))

    display_html_setups(new_setups)
    display_html(stuff_repr)
}
```

**Comment by JanSchulz** [comment]
Nice! Again, learned something new :-)

IMO: we should get an opinion from the notebook people how to name such setup code. I can write the issue there...

**Comment by JanSchulz** [comment]
@daroczig This is an protype of the pander we described above:

```r
library(dplyr)
library(broom)
df <- data.frame(a=0:20, 
                 b=factor((0:20) %% 2, levels=c(0,1), labels=c("a", "b")), 
                 c=factor((0:20) %% 3, levels=c(0,1,2), labels=c("x", "y", "z")))
# ---
library(pander)
# This works in the notebook, juhu!
panderOptions('table.style', 'rmarkdown')
panderOptions("table.split.table", Inf)
pander_new <- function(...){
    t = capture.output(pander(...))
    structure(paste(t, collapse="\n"), class = 'pander_output')
}

knit_print.pander_output <- function(x, ...) {
    cat("in knitprint")
    # from https://github.com/Rapporter/pander/blob/master/R/S3.R#L104
    return(knitr::asis_output(as.character(x)))
}

repr_markdown.pander_output = function(x,...){
    as.character(x)
}

print.pander_output <- function(x) {
    cat(as.character(x))
}
# ---
# or simple use `pander_new(...)` without asignment
x = pander_new(df %>% group_by(c) %>% do(tidy(t.test(a~b, data = .))))
# ---
# in a notebook, this will result in a displayed makdown = html table
# in the console, it will display the markdown code
# in knitr, it will return an knit_asis object
x
# print will force the markdown code, even in the notebook/knitr
print(x)
```

**Comment by JanSchulz** [comment]
Just for the reference, this is what I now have in my startup file and it works great:

```R
# This works in the notebook, juhu!
pander::panderOptions('table.style', 'rmarkdown')
pander::panderOptions("table.split.table", Inf)
pander_ <- function(...){
    t = capture.output(pander::pander(...))
    structure(paste(t, collapse="\n"), class = 'pander_output')
}

repr_markdown.pander_output <- function(x,...){
    as.character(x)
}

print.pander_output <- function(x) {
    cat(as.character(x))
}

ensure.package("pander")
pander <- pander_ # overwrite with a version which works in the display system
```

```R
pander(df %>% group_by(c) %>% do(tidy(t.test(a~b, data = .))))
# -> Produces a nice html table in the notebook
```

**Comment by JanSchulz** [comment]
So to wrap up:

* If this should be fixed, the changes belong to pander and other such libraries, not irkernel -> I will file an bugreport at pander...
* it would be nice if the kernel sets an option to indicate that it is active, so that pander could set the default output to `rmarkdown`
* we should think about (aka talk to the notebook people) and document how to add metadata to repr calls
* It would be nice to have a vignette to show how to implement the above so that it plays nicely with the display system, maybe coordinate with the knitr people

**Comment by JanSchulz** [comment]
The pander issue is now in https://github.com/Rapporter/pander/issues/248, the "change the default when in the kernel" is https://github.com/Rapporter/pander/issues/249

**Comment by JanSchulz** [comment]
Ok, I tried to write a issue in the jupyter_client repo about the metadata and this is what I came up:

**Do it in the kernel**
* + less stuff in the final ipnb file
* + less stuff in the in-memory representation if the notebook in the browser?
* - can lead to multiple styling in the notebook (and is nondeterministic, where the styling shows up), when the kernel is restarted in the middle of the notebook
* - if multiple frontends connect to the same kernel, not all get the styling

**Do it in the notebook**
* + notebook knows what is already displayed and does not display twice, even on kernel restarts
* - more stuff in the ipynb file
* - more stuff in the in-memory representation of the notebook
* - needs changes in the js part and in the nbconvert part

-> This looks more or less that the "in kernel" solutions is probably best and we don't need to bother the notebook people...

issue is now in IRDisplay: https://github.com/IRkernel/IRdisplay/issues/14

**Comment by JanSchulz** [comment]
So, and the vignette issue is in https://github.com/IRkernel/IRkernel/issues/277 and I'm no closing this issue :-)

**Comment by daroczig** [comment]
FTR it's not a bug in `pander`, but as said, `pander` was designed to write to `stout`. The use case that gave life to the `pander` package indeed required writing to `stdout`, as `print` was never called on the object. Anyway, this is doable, but I will have to spend some time on verifying that the required update doesn't brake many things in the reverse dependencies (eg `rapport` pkg).
