### ISSUE TITLE
Change the default output of df %>% colnames() to be valid r code

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/repr#34]
A really great feature of python is that you can c&p the output of 

```python
list(df.columns) # the list is because of the pandas column printouts which wastes screen space :-/
```

and it can be used in a `df[[<c&p output>]]`.

The output of 

```
df %>% colnames()
"a" "b" "c"
```

Can't be c&p because it is missing the `,`. 

So I would be very much for it to change the repr_text output for a vector to include a comma...

**Comment by flying-sheep** [comment]
you mean we should do something else than plain R?

**Comment by JanSchulz** [comment]
Yes... :-/ I really started to hate the current behaviour while analysing my data set... I either need the list in `"xxx", "yyy"` format (`select(one_of(c(...)))`) or in `xxx, xxx` format (`select(xxx, yyy)`)... The `one_of` variant is the more painfull, because I usually have lots of variables and use an extra var to construct the list.

**Comment by flying-sheep** [comment]
i think this isn’t IRkernel’s job.

try

```r
> x <- c('a','b')
> cat(deparse(x))
c("a", "b")
```

**Comment by flying-sheep** [comment]
please don’t take this as me being rude! if you’re of another opinion, say it and we’ll discuss!

this is just my style of dealing with GH issues, as they’re pretty limited.

**Comment by JanSchulz** [comment]
I've the same reservations, but IMO we are already changing it, as we output html for the vector, not plain text. So IMO we can change the output format the same way we alter the output for a data.frame (which becomes a real table...).

Thanks for the deparse trick, I will add the appropriate function to my startup file :-)

**Comment by flying-sheep** [comment]
right, of course.

i said it wrong: it’s not that we change things in general, but that you want us to change the output from presentational to be valid syntax.

and for that, i prefer using the deparse trick (or something more complex and correct that uses sprintf or so)

**Comment by flying-sheep** [comment]
by the way: you might need to add a `substitute` in there if you use it as function. R’s function parameters are actually promises so you’ll need to tell it you want a value here.

**Comment by JanSchulz** [comment]
@flying-sheep ok [/me goes to google `substitute`... comes back with more questions than answers]

Isn't the `cat` doing the final value evaluation? Or do you mean before the `deparse`, like  `cat(deparse(substitute(colnames(...)))`? but in the latter, should colnames not already have done the evaluation? Or is deparse getting the expression `colnames(...)` and would therefore output `"colnames(...)"`? 

And why does it work in this case? Rs `evaluate expressions when they are used` is still kind of mysterious to me...

**Comment by flying-sheep** [comment]
> like `cat(deparse(substitute(colnames(...)))`

like that, yes.

for everything else i have no idea, this is fucking voodoo. i just throw in `substitute` until it works.

i still haven’t figured out when R actually evaluates things and what is passed as expression to e evaluated later.

**Comment by JanSchulz** [comment]
Hm, as far as I understand https://cran.r-project.org/doc/manuals/r-patched/R-lang.html#Promise-objects, the substtute is not needed?

-> `deparse` access the `colnames(...)` promise and therefore there is a value, colnames access `...` and therefore there is a value,  and so the `deparse` get the right value back? I think the dplyr thingys work because there it's actually wrapped and only the promise is passed around? AT least that would explain the mentioning of `Non Standard Evaluation`...

**Comment by JanSchulz** [comment]
Interesting: http://adv-r.had.co.nz/Functions.html#lazy-evaluation

**Comment by flying-sheep** [comment]
well, and all that in the name of making things “easy”

being the arrogant archlinux user i am: easy ≠ simple. better keep things simple than easy.
