### ISSUE TITLE
html handling of strings

### ISSUE THREAD

**Issue by janschulz** [IRkernel/repr#38]
```R
"<!DOCTYPE html><html><title>Text</title></head><body><p>Text</p></body></html>"
```

Will output:

```
"
Text
"
```

Probably because a single string is also a vector and we have a repr_html for vector, which seems to not do any html escapes...

Options?

**Comment by takluyver** [comment]
I'm guessing that anywhere a repr can include string data, it should be html-escaping that string data.

**Comment by janschulz** [comment]
There is this: https://github.com/rstudio/htmltools/blob/master/R/html_escape.R

> License: GPL (>= 2)

**Comment by flying-sheep** [comment]
> I'm guessing that anywhere a repr can include string data, it should be html-escaping that string data.

you mean “anywhere repr_html can include string data”

**Comment by takluyver** [comment]
I do mean that, thanks. Probably markdown too.

**Comment by flying-sheep** [comment]
well, how is notebook markdown defined? nbviewer runs in paranoid safe mode, escaping HTML (even things like `<small/>` and the notebook allows everything…

**Comment by takluyver** [comment]
Looks like it renders HTML to me: http://nbviewer.jupyter.org/gist/takluyver/d5a3692d4d32f44e22f1

In general, I believe any HTML tags are valid in Markdown.

**Comment by flying-sheep** [comment]
ah, ok, then this applies only to markdown cells.

**Comment by janschulz** [comment]
Ok, what should we do here? Use htmltools? If so we essentially relicense irkernel as GPL (as far as I understand licensing...)

**Comment by flying-sheep** [comment]
[umm](https://github.com/IRkernel/repr/blob/da0ce5977621c574d054e58e8fece3df58102af8/DESCRIPTION#L13)

**Comment by janschulz** [comment]
ok, I only checked irkernel... As irkernel does use repr directly, doesn't this make irkernel gpl3, too? 

Anyway: htmltools it is :-)

**Comment by janschulz** [comment]
Or not:

```R
library(repr)
options(jupyter.rich_display = FALSE)
t <- "<strong>Text</strong>"
repr_html(t)
repr:::html.escape(t)
```
 
results in 

```
[1] "\"<strong>Text</strong>\""
[1] "&lt;strong&gt;Text&lt;/strong&gt;"
```

So it seems the html escaping is not applied?

**Comment by flying-sheep** [comment]
> As irkernel does use repr directly, doesn't this make irkernel gpl3, too?

R is also GPL. and i know it’s kinda impossible to *not* provide the source code with R, since R is always stored in expression form, so it’s kinda useless to think about using non-GPL licenses. if we need to for some reason, i’m OK with re-licensing repr, but i think it’s pointless and probably impossible to have any public R code that’s not GPL.

> So it seems the html escaping is not applied?

seems so. we should probably apply it then. and make sure

1. LateX and HTML escaping is applied everywhere (matrices and vectors mainly)
2. that behavior is tested

**Comment by janschulz** [comment]
I've started it here: https://github.com/IRkernel/repr/pull/39
