### ISSUE TITLE
Scope?

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/repr#4]
continuing discussion from [here](https://github.com/IRkernel/repr/commit/3ff5ba87b426ecaba0babe1d53925a6e08c52a3e#commitcomment-10888021). last comments:

@JanSchulz

> I don't argue about that `repr_*.help_files_with_topic` should exist (yes, it should!) but where the best place is.

> IMO the repr package can be more successful if it is the bare minimum API (aka `repr_text.default` via `print`) so that other packages which want to be "representable" can extend it by supplying `repr_*.<object>` for their own objects without getting a hit by many supplied "not-default-repr_*-functions" or having the namespace polluted by things which might surprise users (e.g. they want `print` for lists and only markdown for data.frames by loading pander).

> `repr_*.help_files_with_topic` can exist in the IRkernel package without problem -> it's useable for help pages and if there is really a need for that in other packages, adding a `repr-whatever` packages with more implementations is also an option.

> Thinking about it there needs to be a "API-ish" way to supply `repr_*.data.frame` so that pander/.. can use that to supply their own methods to generate such output when I do a `library(pander)`. Is there a way to overwrite methods for a object type?  

@takluyver 

> It's absolutely my intention that packages should generally specify their own `repr_*.mytype` methods for the types they define. I expect we'll need to provide a few such methods for core types like help, plots and dataframes, though. I'm ambivalent at the moment about whether they live in `repr`, `IRdisplay`, `IRkernel` or even a new package that we make for this purpose (`base_reprs`?).

**Comment by flying-sheep** [comment]
so this is a question about scope.

what classes should have predefined reprs directly in the `repr` package?

the R standard distribution has many classes. should we define reprs for them all? pr even some for 3rd party classes?

i think we should at least have:

* basic R stuff (matrix, data.frame, all kinds of vectors)
* R stuff with a strange print function (`help_files_with_topic`, `recordedplot`)

**Comment by JanSchulz** [comment]
IMO repr should support this usecase:

A package uses the repr system to display some data via markdown or plain text as a fallback (e.g. `ret <- repr_markdown(object); if (ret == NULL){ ret <- repr_text(object)`). A user wants to display only data.frames so writes a `repr_markdown.data.frame` function. Afterwards the system only displays markdown for data.frames but not for any other data type.

I've no idea (as in my R is not good enough to answer it) if that's already possible or if you get the whole already defined `repr_xxx.<object>` if you only want to use the API (e.g. `repr_markdown()`). If a package can load only the API and a user would have to do a explicit `library(repr)` to load the implementations, I'm fine.

**Comment by flying-sheep** [comment]
a package can either

1. Add repr to `Depends:`, which does `library(repr)` if a user loads that other package (so the user will have it all available afterwards)
2. add it to `Imports:` and import it: `import(repr)` (in NAMESPACE) would make everything available in the other package
2. add it to `Imports:` and import a normal or generic function from it: `importFrom(repr, repr_markdown)` would make all `repr_markdown.*` functions available to the package

a user can

1. `require`/`library(repr)` which will make everything that `repr` exports available to the user (like `import * from repr`)
2. `requireNamespace` after which the user has to use `repr::repr_*` to access the functions (like `import repr`)

there’s nothing like python’s `import repr_foo from repr` in R

**Comment by JanSchulz** [comment]
Ok, if a package does `importFrom(repr, repr_markdown)`(and all the other "API" methods), will `repr_markdown` find the `repr_markdown.data.frame` defined in package `repr`? If yes, then IMO `repr` should be split into API (`repr`? `repr-api`?) and implementations (`repr-default`? `repr`?).

**Comment by flying-sheep** [comment]
yes, it will find it. AFAIK, the NAMESPACE will tell R during an `importFrom` that `repr_markdown` is an S3 generic with several methods, [look](https://github.com/IRkernel/repr/blob/57cffa99f13e66316f918ee0e28fc362172cb183/NAMESPACE#L29-L36): it lists an `export(repr_markdown)` and several `S3Method`s

idk if we should separate those. in which cases wouldn’t the user want e.g. `repr_markdown.list`? and even if the user doesn’t like some functions, he/she can still override them.

**Comment by takluyver** [comment]
I suggest that we leave these concerns in one package for now, just because it's easier to work with fewer packages. If it becomes a problem, we can split it up later, but let's allow our architecture to evolve as we use it, rather than trying to plan everything in advance. Does that sound OK?

**Comment by flying-sheep** [comment]
OK
