### ISSUE TITLE
release to cran

### ISSUE THREAD

**Issue by janschulz** [IRkernel/repr#40]
Todo:
* [x]  `R CMD check` on win/mac/linux -> does anything needs changes? -> according to the r-pkgs link below, we have to eliminate every error/warning...
* [x] https://cran.r-project.org/web/packages/policies.html
* [x] http://r-pkgs.had.co.nz/release.html

**Comment by janschulz** [comment]
Things which are hard for us:

```
* - CRAN packages should use only the public API. Hence they should
            not use entry points not declared as API in installed headers nor
            .Internal() nor .Call() etc calls to base packages. Also, :::
            should not be used to access undocumented/internal functions in
            base packages. Such usages can cause packages to break at any
            time, even in patched versions of R.
```

and (for irkernel):
```
   * - Compiled code should never terminate the R process within which
            it is running. Thus C/C++ calls to assert/abort/exit, Fortran
            calls to STOP and so on must be avoided. Nor may R code call q().
```

**Comment by janschulz** [comment]
After https://github.com/IRkernel/repr/pull/41, we now have IMO everything document, which comes in `R CMD check`. So are there any blockers for a release on CRAN?

I went through the current issues and labeled them bug/enchancement and added the ones I thought relevant to a [0.5 milestone](https://github.com/IRkernel/repr/milestones/0.5). Please change if I did something wrong...

**Comment by flying-sheep** [comment]
good work!

we need this for IRkernel as well!

**Comment by janschulz** [comment]
First repr, then irdisplay, then irkernel...

**Comment by janschulz** [comment]
So, we have no more issues in the 0.5 Milestone, all tests pass on travis and windows and AFAIK all Notes and Warnings are either dealt or explained in https://github.com/IRkernel/repr/blob/master/cran-comments.md

-> We are good to release?

@flying-sheep Can you cut a release and upload it to CRAN? AFAIK you have to do the cran upload as you are listed as Maintainer.

**Comment by flying-sheep** [comment]
done: ftp://cran.r-project.org/incoming/

**Comment by janschulz** [comment]
Thanks!

**Comment by janschulz** [comment]
It's not anymore there?

**Comment by flying-sheep** [comment]
haha, that’s just for stuff that nobody looked at yet.

now the review process has started.

**Comment by janschulz** [comment]
@flying-sheep Any news? :-)

**Comment by flying-sheep** [comment]
yeah, i need to get around doing some stuff for it. mailed it to you

**Comment by janschulz** [comment]
Another try? :-)

**Comment by flying-sheep** [comment]
sure!

**Comment by janschulz** [comment]
@flying-sheep Any news? IRdipslay would be next...

**Comment by flying-sheep** [comment]
thanks for the reminder! i already uploaded a new version, but forgot to click the verification link

**Comment by janschulz** [comment]
And it's done: https://cran.r-project.org/web/packages/repr/index.html :-)

**Comment by flying-sheep** [comment]
good to know. i apparently check github more often than mails

**Comment by flying-sheep** [comment]
oh, and: :tada: :birthday: :fireworks:

**Comment by takluyver** [comment]
:-) Well done!
