### ISSUE TITLE
plot size only evaluated at the end of a cell?

### ISSUE THREAD

**Issue by janschulz** [IRkernel/repr#42]
The following will output both plots in the same size, if both of them are in the same cell:

```r
set_plot_size <- function(width = 7, height = 7){
    options(repr.plot.width = width) 
    options(repr.plot.height = height)
}
set_plot_size(3,1)
qplot(1:10,1:10)
set_plot_size(3,3)
qplot(1:10,1:10)
```

**Comment by janschulz** [comment]
The problem is that the plot is only sent if the next plot is "different": https://github.com/IRkernel/IRkernel/blob/f233b889873145131d321d4aa66da9034d77e642/R/execution.r#L236

But at that place, the size is already redefined. So I think irkernel should record the plot size by setting an attribute on the recordedplot object and `repr_xxx.recordedplot` should take that into account by overwriting if no plot size attribute is set in the call.

**Comment by janschulz** [comment]
E.g.:

```r
repr_png.recordedplot <- function(obj,
	width     = NULL, [...]){
    if (is.null(width)){
        if (has_attr(".plot_width")){
              width = get_attr(".plot_width)
        } else {
              width = getOption('repr.plot.width')
        }
     }
     [... same for height ...]
}
```

**Comment by flying-sheep** [comment]
cool idea! nor a repr bug though

**Comment by janschulz** [comment]
But needs fixes at both sides :-/

**Comment by flying-sheep** [comment]
i don’t think so. we just attach them to every recordedplot object anyway, right?

so we can just adjust our `repr_*` call to:

```r
formats[[mime]] <- mime2repr[[mime]](plotobj, attr(plotobj, 'width'), attr(plotobj, 'height'))
```

**Comment by janschulz** [comment]
You are right: https://github.com/IRkernel/IRkernel/pull/292

**Comment by balta2ar** [comment]
@janschulz @flying-sheep I'm sorry for putting my oar in, but how do I set plot size? Out of the box they are huge and take whole page width. I've tried you code but it gives me an error:
``` r
set_plot_size <- function(width = 7, height = 7){
    options(repr.plot.width = width) 
    options(repr.plot.height = height)
}
set_plot_size(3,1)
hist(1:10)

Error in replayPlot(obj): invalid graphics state


Error in replayPlot(obj): invalid graphics state


Plot with title "Histogram of 1:10"
```

**Comment by balta2ar** [comment]
Okay, `par(pin=c(2,1))` reduces plot size, but it leaves gigantic white margins all around. The output cell is still huge.

**Comment by balta2ar** [comment]
I don't know why but after I did `library(ggplot2)` and `qplot(...)`, it worked... Guys, do you think it's worthwhile adding these two questions to FAQ section:

1. Q. When I execute a cell, R window flashes for a moment and disppears. How to get rid of this annoying window? A. Use `options(device=pdf)` (by the way, why isn't it the default behavior?).
1. Q. How to change plot size? A. Use this: `library(repr)` then `options(repr.plot.width=4, repr.plot.height=3)`.

**Comment by flying-sheep** [comment]
good points!

**Comment by janschulz** [comment]
> Q. When I execute a cell, R window flashes for a moment and disppears. How to get rid of this annoying window? A. Use options(device=pdf) (by the way, why isn't it the default behavior?).

Actually: why is this actually happening? I never saw this (on windows)?

**Comment by balta2ar** [comment]
@flying-sheep Thanks! Here is my `sessionInfo()`:
```
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=C               LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] magrittr_1.5    IRdisplay_0.3   tools_3.2.4     base64enc_0.1-3 uuid_0.1-2     
 [6] stringi_1.0-1   rzmq_0.7.7      IRkernel_0.5    jsonlite_0.9.19 stringr_1.0.0  
[11] digest_0.6.9    repr_0.4        evaluate_0.8.3 
```

Maybe it's something in my `~/.Rprofile`. Could you take a look? http://ix.io/wWg/r

Particularly I've been worried about these lines:
``` r
setHook(packageEvent("grDevices", "onLoad"),
        function(...) grDevices::X11.options(width=8, height=8,
                                             xpos=0, pointsize=10,
                                             type="nbcairo"))  # Cairo device
                                             #type="cairo"))    # other Cairo dev
                                             #type="xlib"))      # old default
```
But after I commented them out, restarted ipython notebooks and executed the code block, nothing has changed.

Is there any way to determine in `~/.Rprofile` whether it's running inside ipython's kernel or a regular R session? Then I could conditionally call `options(device=pdf)`.
