### ISSUE TITLE
repr_help_files_with_topic_generic should catch errors and show no traceback

### ISSUE THREAD

**Issue by janschulz** [IRkernel/repr#44]
```R
?IRkernel
Error: c:/data/external/R/IRkernel/man/IRkernel.Rd:12-16: Tag \code not expected in code block
Traceback:

1. prepare_mimebundle(obj, .self$handle_display_error)
2. repr_text(obj)
3. repr_text.help_files_with_topic(obj)
4. repr_help_files_with_topic_generic(obj, tools::Rd2txt)
5. capture.output(Rd2_(rd, package = pkgname, outputEncoding = "UTF-8"))
6. evalVis(expr)
7. withVisible(eval(expr, pf))
8. eval(expr, pf)
9. eval(expr, envir, enclos)
10. Rd2_(rd, package = pkgname, outputEncoding = "UTF-8")
11. writeSection(Rd[[i]], sections[i])
12. writeCodeBlock(section, tag)
13. stopRd(block, Rdfile, "Tag ", tag, " not expected in code block")
14. stop(msg, call. = FALSE, domain = NA)
```

**Comment by flying-sheep** [comment]
heh, i think i should rather fix the help page. it’s OK if broken help pages throw errors!

**Comment by janschulz** [comment]
> i think the repr method should propagate errors. broken docs are broken, why paper over it?

In this case it should just send a shorter message because no one benefits from seeing our call stack... It makes a lot more sense to output the name instead and maybe what to do (report it in the package).

**Comment by flying-sheep** [comment]
that makes sense.

we can simply wrap the [conversion function call](https://github.com/IRkernel/repr/blob/dbf491a3604ced82b04b48a7bd4959f648735cb6/R/repr_help_files_with_topic.r#L47) into a tryCatch, and just make the error message the output (formatted in red or so with LaTeX/HTML)

**Comment by janschulz** [comment]
> formatted in red or so with LaTeX/HTML

IMO this won't work currently: we are in repr_text, so we can`t format :-( even using streams isn't possible as that would mean that repr should gain access to IRdisplay or IRkernel functions (=dependency loop). 

But that leaves another question: if we ever want to get help content into a pager, how would that be formatted? Add a `repr_page` way?

**Comment by flying-sheep** [comment]
> IMO this won't work currently: we are in repr_text, so we can`t format :-(

no, i mean for the other two reprs

> if we ever want to get help content into a pager

what do you mean? help already shows in a pager

**Comment by janschulz** [comment]
Right now it doesn display anything on this side:

```
DEBUG: Executing code: ?IRkernel::jupyter_option_defaults
DEBUG: Value output...
DEBUG: Showing pager: List of 3
 $ text/plain: chr "IRkernel               package:IRkernel                R Doc
umentation\n\n_\bA_\bn _\bR _\bk_\be_\br_\bn_\be_\bl _\bf_\bo_\br _"| __truncate
d__
 $ text/html : chr "\n<table width=\"100%\" summary=\"page for IRkernel {IRkerne
l}\"><tr><td>IRkernel {IRkernel}</td><td style=\"text-align: right;"| __truncate
d__
 $ text/latex: chr "\\inputencoding{utf8}\n\\HeaderA{IRkernel}{An R kernel for J
upyter.}{IRkernel}\n\\aliasA{IRkernel-options}{IRkernel}{IRkernel.R"| __truncate
d__
DEBUG: Sending msg status
DEBUG: Sending msg execute_reply
```

But nothing shows up in the notebook?!

**Comment by flying-sheep** [comment]
wait what? why is `page` boken?

printing `reply content` gives me this (wrong) thing:

```r
$status
[1] "ok"

$execution_count
[1] 1

$payload
$payload[[1]]
$payload[[1]]$source
[1] "page"

$payload[[1]]$data
$payload[[1]]$data$data
$payload[[1]]$data$data$`text/plain`
[1] "[snip]"

$payload[[1]]$data$data$`text/html`
[1] "[snip]"

$payload[[1]]$data$data$`text/latex`
[1] "[snip]"

$payload[[1]]$data$metadata
named list()

$user_expressions
named list()
```

**Comment by flying-sheep** [comment]
it broke at some point. fixed indbf491a3604ced82b04b48a7bd4959f648735cb6

**Comment by janschulz** [comment]
Probably https://github.com/IRkernel/IRkernel/commit/3ff41c733aaba801823217135e5371fc934292eb :-) 

I've actually no clue what this did and why... -> could you add more descriptive commit messages? http://chris.beams.io/posts/git-commit/#why-not-how :-)

**Comment by flying-sheep** [comment]
good point. i extracted the mimebundle building logic to simplify `handle_value`. now `handle_value` is clean and übersichtlich (sorry, that word has no english translation)

**Comment by janschulz** [comment]
Ok, the bug in our docs is fixed, And the original issue here (not showing the stacktrace if there are errors) is an enhancement -> not a blocker...

**Comment by flying-sheep** [comment]
let’s use #45 for this.
