### ISSUE TITLE
html data.frame does not use labels in factors

### ISSUE THREAD

**Issue by janschulz** [IRkernel/repr#47]
```R
df <- data.frame(a = 1:4, b=factor(1:4, levels=1:4, labels=c("A", "B", "C", "D")))
df
```

results in the following:

![2016-04-25_105944](https://cloud.githubusercontent.com/assets/890156/14778718/d8399eba-0ad4-11e6-9bb3-576a0b702b90.png)

Printing does the right thing:

```
  a b
1 1 A
2 2 B
3 3 C
4 4 D
```

```R
df["b"]
```

Also prints the labels...

**Comment by flying-sheep** [comment]
…why? i thought we test

**Comment by janschulz** [comment]
The repr stuff itself is untested? Only html/latex escaping and the "make it shorter" stuff with the ellipses are currently tested... https://github.com/IRkernel/repr/issues/5 is still open :-)

**Comment by flying-sheep** [comment]
ah, right. i thought the ellipsis stuff would contain things like factors

**Comment by ColCarroll** [comment]
Any suggestions for temporary fixes? I tried using `devtools::install_version` to install an old version, but it appears only 0.6 is on CRAN now.

**Comment by janschulz** [comment]
@ColCarroll The fix is not yet merged: see #51 for the PR

After that is merged, you can use `devtools::install_github("irkernel/rep")` to install the new version

**Comment by ColCarroll** [comment]
Thanks so much for the quick fix!

**Comment by flying-sheep** [comment]
thank @karldw!
