### ISSUE TITLE
explicitly import and test for non-base functions

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/repr#48]
[see here](http://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2015/06/29#n2015-06-29) why our CRAN submission didn’t get through. `R CMD check --as-cran` does more stuff since some weeks.

**Comment by janschulz** [comment]
I can reproduce on r-devel (fun... needed to reinstall my complete R environment because of teh way I had them installed before...). Unfortunately, the suggested fix does not work because NAMESPCE is regenerated by roxigen2:

```
[...]
repr_text.data.frame: no visible global function definition for
  'capture.output'
repr_text.default: no visible global function definition for
  'capture.output'
repr_text.matrix: no visible global function definition for
  'capture.output'
Undefined global functions or variables:
  cairo_pdf capture.output dev.off jpeg pdf png replayPlot svg
Consider adding
  importFrom("grDevices", "cairo_pdf", "dev.off", "jpeg", "pdf", "png",
             "replayPlot", "svg")
  importFrom("utils", "capture.output")
to your NAMESPACE file.
```

**Comment by flying-sheep** [comment]
```bash
grep importFrom R/*.r
```

**Comment by janschulz** [comment]
https://github.com/IRkernel/repr/pull/49
