### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by takluyver** [IRkernel/repr#5]
Missing tests:

* [x] vectors (different data types); diff length (cutoff) is handled [MD, latex, HTML]
* [x] data.frame (different data types, including factors) [MD, latex, HTML]
* [x] "cutoff" of long dataframes/vectors
* [x] latex/html escapes

----

We should have some. For all the packages, really, but `repr` is probably the easiest bit to test. We can look into using [testthat](https://github.com/hadley/testthat).

For the kernel, there should soon be a test framework as part of Jupyter that starts a kernel and tests it by communicating with it.

**Comment by JanSchulz** [comment]
Some of the kernel functionaly could be refactored into small functions (e.g. `is_complete()` could become a function which takes code and returns a status) which can be tested with testhat.

**Comment by JanSchulz** [comment]
This can now be closed? Or use this to add tests on travis?

**Comment by JanSchulz** [comment]
@karldw do you have any experience with makeing R tests run on travis?

**Comment by takluyver** [comment]
It looks like it should be simple (famous last words!):

https://docs.travis-ci.com/user/languages/r

**Comment by karldw** [comment]
It looks not-terrible.  Before accepting the pull request, could one of you maintainers do steps 1 and 2 [here](https://docs.travis-ci.com/user/getting-started/) to sign up for Travis?

**Comment by flying-sheep** [comment]
> This can now be closed? Or use this to add tests on travis?

we should add tets for all repr functions.

**Comment by janschulz** [comment]
Ok, this isn't "ready", but at least we have some tests now :-)

**Comment by flying-sheep** [comment]
i added some data frame tests regarding factors.

idk what you want to test in vectors…

**Comment by flying-sheep** [comment]
Let’s close this. If someone has ideas about what to test in vectors, we can open another issue or straight up add the tests

**Comment by janschulz** [comment]
IMO: all repr methods should at least test that the interface is right: returns a string. We should probably add a helper for that (`assert_conforms_to_repr_api(...)' ). 

For vectors and so on: normal input and some edge cases: NULL, empty input, too long (ellipsis), unicode...

I think there was some code coverage tool for R...

**Comment by flying-sheep** [comment]
oh, and check if some options work, e.g. string vector quoting.

coverage:

* https://github.com/jimhester/covr
* https://github.com/MangoTheCat/testCoverage

you don’t have to leave GitHub these days…

**Comment by flying-sheep** [comment]
let’s discuss in #56
