### ISSUE TITLE
new mode: no rich display for primitives

### ISSUE THREAD

**Issue by janschulz** [IRkernel/repr#52]
Currently we use two modes: "rich" or "not rich". I would like to introduce a third "rich, but not for primitive data like vector/..."

**Comment by mikecroucher** [comment]
I like this idea!  So, at the moment, this is controlled by 

    options(jupyter.rich_display=FALSE)

What should the interface look like? Currently `jupyter.rich_display` is boolean which is insufficient. Can this be changed here?

**Comment by flying-sheep** [comment]
sure it can. as long as we still interpret `TRUE` and `FALSE` to mean “rich” and “not rich”, respectively, we can add as many additional/alternative values as well.

maybe we should just add a third value but leave `TRUE` and `FALSE` as the only things meaning  “rich” and “not rich”, or we add three new non-boolean values (e.g. 0,1,2 or `'off'`,`'basic'`,`'on'`. i’m against “smart”)

**Comment by flying-sheep** [comment]
this issue is in the wrong repo btw.

**Comment by janschulz** [comment]
depends: original I wanted to implement it in repr by telling the S3 mechanismus to use the next function.

**Comment by flying-sheep** [comment]
ah OK. well, `jupyter.rich_display` is in IRkernel and we cleared up the scope of repr already.

maybe i should put it into the README.

**Comment by janschulz** [comment]
After the last discussions my understanding of repr is, that it produces text output and does NOT has any side effects (call pager, etc) and can't be changed by any options. 

If that's so, then this feature has to be implemented in the IRkernel.

**Comment by flying-sheep** [comment]
exactly. the options are to regulate how the reprs look, but repr’s scope ends with its caller:

if someone calls `repr_foo(thing)` that means they want to have the `foo` format representation of a `class(thing)` object, and we should return that if possible.

**Comment by flying-sheep** [comment]
hi @janschulz, thanks for closing those old issues, but don’t you want the third `jupyter.rich_display` value here anymore?

we don’t have an issue for it in IRkernel yet, right?

**Comment by jlorince** [comment]
I know I'm about 5 years late to the party, but does anyone know of a way to achieve this functionality? Specifically I would like to configure output such that dataframes still render html but primitives render as plaintext ( in a notebook )

**Comment by flying-sheep** [comment]
I accept PRs! (And actually comaintainers, I’m spread pretty thin)
