### ISSUE TITLE
mime2repr function return NULL

### ISSUE THREAD

**Issue by chkPocket** [IRkernel/repr#60]
```r
> library(repr)
> setClass('Test', representation(n = 'character'))
> x = new('Test')
> x
An object of class "Test"
Slot "n":
character(0)

> mime2repr[['text/html']](c(x,x))
[1] "<ol>\n\t<li>NULL</li>\n\t<li>NULL</li>\n</ol>\n"
```

Why does this function return NULL elements?

**Comment by flying-sheep** [comment]
hmm, it should return basically:

```r
sprintf("<ol>
	<li>%s</li>
	<li>%s</li>
</ol>", capture.output(print(x)), capture.output(print(x)))
```

**Comment by chkPocket** [comment]
How to determine the element in list whether is unreprable. @flying-sheep

**Comment by flying-sheep** [comment]
uh, the only line i added in the commit in which i closed this. it’s linked above your comment.

**Comment by chkPocket** [comment]
OK, got it. thanks!

**Comment by flying-sheep** [comment]
OK, cool! you got me confused a bit here :smile: 

to elaborate on the code: the `repr_*.NULL` always returns `NULL` (i.e. not the string `'NULL'`, but the object `NULL`)

that’s why i don’t simply check if any repr_function returns NULL like this: `any(vapply(mapped, is.null, logical(1)))`

instead i check if any repr of a non-NULL object returns NULL.
