### ISSUE TITLE
Harden matrix/df repr

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/repr#65]
we have many problems regarding this stuff. i think after #64 has made it in, we should rework this like so:

1. decompose into sliced parts of the df/matrix if larger than limits. e.g.:

	```r
	parts <- list(left = ..., right = ...)
	type <- 'horizontal'
	# or
	parts <- list(full = obj)
	type <- 'full')
	```

2. transform parts into `list` of `matrix` of `character`, similar to:

	```r
	formatted_parts <- lapply(parts, function(part)
		if (is.matrix(part))
			format(part)
		else
			vapply(part, format, character(nrow(part))))
	```

3. glue together parts with ellipses:

	```r
	rv <- switch(type,
		full = parts$full,
		horizontal = cbind(parts$left, ellip.h, parts$right),
		...)
	```

**Comment by janschulz** [comment]
If the splitting is done in "native" code (dplyr, data.table), then this would also prevent the potential memory blowup and performance hit when we have to display a large data.table. :-)

My preference for the first step would be:

```R
parts <- list(ul = ..., ur = NULL, ll = NULL, lr = NULL)
```

parts could probably be a list of `data.frame`s as the parts are probably small enough to not matter if they get converted at that step.

In the glue step that would result in a simple check if `parts$ur` is non `NULL` to see of there needs to be an ellipsis between columns and a check for `parts$ll` if there needs to be an ellipsis between upper and lower part of the frame.

The only bad thing I see here is that we potentially have to do it multiple times for all formats. Maybe a `repr_convert_to_display_object(obj)` before calling `repr_...()` on it? The default implementation would just return, but the `repr_convert_to_display_object.data.frame`, `....matrix`, `....data.table`, and `....tbl_df` would return a "everything converted to characters"-`data.frame` including ellipses? But that would also mean that `repr_html(obj)` would return something different than the "prints" in the notebook :-/

**Comment by flying-sheep** [comment]
i don’t like this approach, it’s not obvious, as the `NULL` entries are arbitrary. i don’t like opportunity for misspelling.

also remember: `is.null(list()$nonexistant)`

better than my original idea:

```r
type <- if (...) {
	left <- ...
	right <- ...
	parts <- list(left, right)  #always an unnamed list with all parts
	'horizontal'
} else ...

formatted_parts <- lapply(parts, ...)

switch(type,
	# use the variables only defined in case “type == 'horizontal'”
	horizontal = cbind(left, ellip.h, right),
	...)
```

**Comment by janschulz** [comment]
> i don’t like this approach, it’s not obvious, as the NULL entries are arbitrary.

It's either NULL or a part of the original stuff (and after converting a `data.frame`), so `is.null(list()$nonexistant)` is not an issue, because we only touch the part if it is non-NULL.

I don't get the argument about misspelling: that's what unittests are for?

The nice thing about this approach is that you basically get the code for all 4 cases (fits completely, split horizontal, split vertically, split both) with just a null check in the conversion function (if part is NULL, return NULL) and the final join is just 

```
if (!is.null(parts$ur)) {
   upper = cbind(parts$ul, ellip.h, parts$ur)
   lower = cbind(parts$ll, ellip.h, parts$lr)
} else {
   upper = parts$ul
   lower = parts$ll
}
if (!is.null(lower )) {
   ret = cbind(upper, ellip.h, lower)
} else {
   ret = upper
}
```

**Comment by flying-sheep** [comment]
> we only touch the part if it is non-NULL

got it, sorry.

> you basically get the code for all 4 cases

we have the following cases

* 2×cbind + 1×rbind (or the other way round)
* 1×cbind
* 1×rbind  (this would be the only thing we don’t repeat in your version)
* nothing

my way has a small bit of duplication but is much simpler and less opportunity for errors:

```r
rv <- switch(type,
	both = rbind(
		cbind(ul,            ellip.h,      ur),
		ellip.limit.vec(rep(ellip.v, cols + 1L), cols, ellip.d),
		cbind(ll,            ellip.h,      lr)),
	horizontal = cbind(left,  ellip.h, right),
	vertical   = rbind(upper, ellip.v, lower),
	full = full)

**Comment by janschulz** [comment]
So basically the difference between my version and yours is whether to implement the "what type it is" in the data structure itself or use a separate variable and whether to use different variables depending on the type and the rest is NULL (or not initialized) or a standardized data structure where some of them could be NULL.

IMO it's basically the same :-) -> Whoever does the implementation gets to choose?

How do you stand on the `repr_convert_to_display_object(obj)` to not do the converting multiple times?

**Comment by flying-sheep** [comment]
the way i did it, i use [those lines](https://github.com/IRkernel/repr/blob/8c3eb94cda99f807f75310e85256fc7409c4e467/R/repr_matrix_df.r#L92-L104) to convert every part to a character matrix. so the `function(part)` is basically your `repr_convert_to_display_object`.

i adapted the tests to the new return value of `ellip.limit.arr` (which used to preserve the class).

i think this is now much cleaner and less edge-casey.
