### ISSUE TITLE
Add packageIQR reprs

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/repr#7]
`data()` returns a `packageIQR` list object, with a magic print function.

we should catch and prettyprint that.

**Comment by JanSchulz** [comment]
Is overwriting pager (whatever is currently wrong with it) not be enough already?

`print(data())` won't "print" anything, so a empty string is returned and the content is send via `pager()` as a page (https://ipython.org/ipython-doc/dev/development/messaging.html#payloads) or as a simple text/plain display_data message?

**Comment by flying-sheep** [comment]
that’s OK as well.

probably we should make configurable in the kernel if we want pager functions to give volatile results (via pager) or permanent ones.

i think jupyter/jupyter_notebook#56 could also help

**Comment by janschulz** [comment]
vignette probably would also benefit from this: `vignette()` also returns such a type and `utils:print.vignette()` could also be remove to send the vignette in a page...

**Comment by janschulz** [comment]
Ok, following the trail:


* `utils:::print.packageIQR`-> calls `file.show`
* `file.show` calls `getOption("pager")` if it is available

-> IMO we only have to put our own pager into that function and be done...

**Comment by janschulz** [comment]
This is the alternative (`utils:::print.packageIQ` does it a lot more complicated, but that also looks better):

```R
repr_text.packageIQR <- function(obj, ...){
    # colnames(obj$results)
    # "Package" "LibPath" "Item" "Title"
    vignettes <- paste('- "', obj$results[,3], '": ', obj$results[,4], '(', obj$results[,1], ')', sep="", collapse="\n")
    paste("# ", obj$title, "\n\n", vignettes, sep="")
}
```

**Comment by flying-sheep** [comment]
sep and collapse is weird. i don’t think it works as expected. i think you need to first collapse then paste.

and i’d prefer `sprintf` here. it’s much less confusing

**Comment by janschulz** [comment]
should we go down the repr route or simply set pager to something in IRkernel? We anyway have to do the latter and that way we get a page instead of output.

**Comment by flying-sheep** [comment]
repr should be independent from IRkernel.

if we call `repr_*(packageIQR)`, we don’t want to see a pager opened, just like we don’t want something plotted to the current device or a webserver opened. that’s kinda the point of repr.

so yeah: roll our own or temporarily replace the current pager.

**Comment by janschulz** [comment]
But implementing it there means that we don't have a way to put such things in the pager...

**Comment by flying-sheep** [comment]
implementing what where? sorry, i’m confused. what are the options?

* do nothing and let the print function open the pager for us
* create a repr function for the class

**Comment by janschulz** [comment]
-> If repr has a special method for it, print will never be called on such an object, so it never gets to pager...

That's IMO the biggest problem right now, that when we implement repr methods for objects, all original print methods which do something else than  `cat("text")` (e.g. call pager or oben a webbrowser) are out of reach and in some cases it is actually desireable to have a different result than text in the output area.

**Comment by flying-sheep** [comment]
i’ll show you what i mean:

```r
repr_text.packageIQR <- function(obj, ...) {
	old_pager = getOption('pager')
	rv <- NULL
	options(pager = function(...) {
		rv <- ...
	})
	tryCatch(print.packageIQR(obj), error = identity)
	rv
}
```

**Comment by janschulz** [comment]
Ive no problem of building a functions which simple converts such obj to strings (even without the pager hack), but I want that a pager is actually used to send the stuff so that it ends up in page in the notebook and not in the output area.

But if a repr_text method for such stuff exists thats not anymore possible unless we 

* build some hooks into the repr_* system to single that something should go to the pager instead of the output area (which would still break a lot of things, eg. what happens if the user writes a `repr_html.packageIQR()`?)
* add some `repr_should_go_to_pager()` system and let the kernel use that to decide if some output shoudl go to the pager
* do not build repr functions for such objects but build print.* functions (or in this case simple overwrite the pager options)

Currently repr is build on the assumption that every object should be converted to a string (that part is ok) and should end up in the output area of the notebook (that part is not).

**Comment by flying-sheep** [comment]
we have that exact thing implemented in IRkernel [`getOption(jupyter.pager_classes`](https://github.com/IRkernel/IRkernel/blob/a939fe9ac6667c9b565bc6bb7bf31cad73512b94/R/options.r#L9-L10)

**Comment by janschulz** [comment]
Outch... PRs incomming... never noticed that thing...

**Comment by flying-sheep** [comment]
it’s pretty recent :smile:
