### ISSUE TITLE
Notebook strips spaces in string

### ISSUE THREAD

**Issue by dpavlic** [IRkernel/repr#75]
It seems extra spaces will get 'eaten' when using the notebook, which caused some tears earlier. An easily reproducible example. In the notebook:

```
x <- c('one space', 'two  space')
unique(x)
```

Outputs:

**'one space' 'two space'**

Jupyter _console_ on the other hand gives what would be expected:

**[1] "one space"  "two&#160;&#160;space"**

(Note that it seems the github markdown editor also strips that space unless I use unicode escaping to show it).

**Comment by takluyver** [comment]
I guess this is because the notebook uses HTML display, and the spaces are still there in what we send, but HTML collapses consecutive spaces. If that's the case, than our HTML escaping of strings should turn space into `&nbsp;` which doesn't get collapsed.

**Comment by flying-sheep** [comment]
but &nbsp; is 00A0, which is differently from space (0020).

we could use [`white-space: pre-wrap`](https://developer.mozilla.org/de/docs/Web/CSS/white-space) if a string contains consecutive spaces…

**Comment by takluyver** [comment]
Sure, that's probably better.
