### ISSUE TITLE
to have a pdf-file of my fig and inline graphics at the same time

### ISSUE THREAD

**Issue by aakhmetz** [IRkernel/repr#76]
I tried to check the thread, but couldn't find it. If I use "pdf("out.pdf") ... dev.off()", then I get a pdf-file with my plot, but no inline graphics. If I don't write pdf() at the beginning, I get the inline graphics successfully shown, but no pdf-file in my folder.

How do I do that with "repr"-something?

**Comment by takluyver** [comment]
We use a graphics device that records plots and then displays them from the recorded data after the cell has finished running. If you switch to a different graphics device in the cell, the plot doesn't go to the 'recorder'. It's probably possible to use some combination of `recordPlot()` and `replayPlot()` to send it to two devices. I'm sure @flying-sheep can provide more info.

**Comment by flying-sheep** [comment]
yes that. you either plot twice or record once and replay twice.

**Comment by takluyver** [comment]
I think this is common enough, and the answer sufficiently non-obvious, that it would be good to put that explanation in the FAQ :-)

**Comment by flying-sheep** [comment]
the answer is exactly the same as if you didn’t use the R kernel though.

if you want to plot something to pdf and the default device in other environments you need to do exactly the same.

**Comment by aakhmetz** [comment]
Ok, thanks!

No, it's not the same with python kernel - you can do inline graphics and then savefig to pdf within one cell. With R, you need to specify first the device for output.

Finally, I found the way with replayPlot as you proposed. But I spent some time on searching - I found it in one of the examples from IRDisplay repo. Google search was not very helpful: it gave me the links only on how to change the size of the plot in IRKernel, but not on how to save the figure. That's why I agree, it would be helpful to put such info in FAQ or any manual. 

> yes that. you either plot twice or record once and replay twice
Why do you need to replay twice? I believe one time is enough
```r
library("repr"); 
plot_point_sizes <- c(5,4,14); 
options(repr.plot.width=plot_point_sizes[1], repr.plot.height=plot_point_sizes[2], 
        repr.plot.pointsize=plot_point_sizes[3]);
[...]
plot(...)
[...]
p <- recordPlot()
```
then in the following cell:
```r
pdf("MyFigure.pdf",width=plot_point_sizes[1],height=plot_point_sizes[2],pointsize=plot_point_sizes[3]); 
replayPlot(p); 
dev.off()
```

**Comment by janschulz** [comment]
> No, it's not the same with python kernel - you can do inline graphics and then savefig to pdf within one cell. 

Maybe a bit of background: IRkernel only catches the plot when it is actually drawn. In python the object describing the final plot (matplotlib Figure) is "found" due to the global state matplotlib maintains when using the the pyplot interface. So what is actually happening in the pyhton kernel is that 

```
# build the matplotlib Figure (might be implicitly in the global mapl state)
# save the Figure as a image file (actual draw)
# the matplotlib figure is found in the global state and plotted by ipython (probably drawn again)
```

This would be equivalent to using ggplot and doing something like this

```
# build the ggplot object
# save the ggplot plot to a image file
# put the ggplot object in the last line so that it is printed and then captured by the IRkernel (actually by the evaluate" package)
```

So in both cases, the actual drawing is done twice (not sure if either ggplot or matplotlibs Figure caches the "canvas").

> Why do you need to replay twice? I believe one time is enough

You are probably doing two "draws" implicitly. If you are only after less shown code, your way is fine, but if you are after speed, you won't get any speed savings because the (in some case expensive) draw happens twice. If you want to save time, it's probably easiest to use `IRdisplay` and `display_png()` (if you save as png).

**Comment by takluyver** [comment]
I think @flying-sheep's "if you didn’t use the R kernel" was a comparison with using R outside Jupyter, rather than a comparison with the IPython kernel.

I still think a FAQ entry for this would be nice, even though it's not specific to IRkernel.

**Comment by flying-sheep** [comment]
exactly. i’m not sure if we should start putting general R advice in our FAQ.

from my experience, a FAQ has to be short, else people don’t bother using it and file an issue anyway. idk if we should sacrifice space for generic R questions when others are sufficient.

**Comment by takluyver** [comment]
I see FAQs mostly as a convenient resource to point to when people ask common questions. Of course, you can link to an issue where you've answered it, but:

- Issues tend to be cluttered with the specifics of a particular case, and additional discussions like this ;-), so it's less useful to someone else trying to make sense of it.
- I can usually find an FAQ I know exists quicker than an issue I vaguely remember.

I agree that there shouldn't be too many FAQs, though, so let's leave this for now and see how F it's A-ed. :-)

**Comment by aakhmetz** [comment]
Thank you for clarification! 

My problem with recordPlot() was that I hadn't known about its existence.

**Comment by flying-sheep** [comment]
i also have that problem with issues, except if i remember a term that’s specific enough or even occurs in the title (firefox searches page titles when typing in the address bar)
