### ISSUE TITLE
salvus.html() won't show image from /tmp

### ISSUE THREAD

**Issue by DrXyzzy** [IRkernel/repr#80]
Start with valid testfile.png and copy it to /tmp. This fails with broken image icon
```
salvus.html('<img src="/tmp/testfile.png">')
```
but this works
```
salvus.file("/tmp/testfile.png")
```

**Comment by DrXyzzy** [comment]
sorry wrong repo

**Comment by takluyver** [comment]
I don't know if you have worked it out, but it's an issue with the HTML you're writing. The path in `src=` is relative to the root directory of the server - which is not normally the root directory of the computer running it. In Jupyter, the root directory of the server is the directory in which you launched the notebook. So you can't just refer to an image in an arbitrary on-disk directory.

**Comment by DrXyzzy** [comment]
Appreciate the cautionary note. Sorry for the noise, but nice to hear from the IRkernel team. SMC issue is sagemathinc/smc#1184 It was my bug, IRkernel is working fine.
