### ISSUE TITLE
Create documentation with an example of how to use this?

### ISSUE THREAD

**Issue by dfrankow** [IRkernel/repr#85]
I'd like to print an image in R in a Jupyter notebook. See also http://stackoverflow.com/questions/43415276/how-to-display-a-table-of-images-in-r-output-in-a-jupyter-notebook.

I think this repo probably is related to that desire, but through IRKernel? I'm ignorant enough that I don't know how this all fits together, and creating an example or two would be quite helpful.

**Comment by flying-sheep** [comment]
hi! sorry for the confusion:

1. `repr` creates image and text format data from objects (“representations”)
2. `IRkernel` provides the R kernel for jupyter notebooks and consoles
2. `IRdisplay` is an user interface for going from object to a table or image displayed in jupyter notebook:

    ```r
    library(IRdisplay)
    display(obj)
    display_html('<i>hi!</i>')
    display_jpeg(file = 'filename.jpg')
    ```

**Comment by dfrankow** [comment]
Very helpful, thank you!

I transferred this to [the wiki](https://github.com/IRkernel/repr/wiki).
