### ISSUE TITLE
Plot objects aren't getting returned in prepare_mimebundle

### ISSUE THREAD

**Issue by jeffwong** [IRkernel/repr#87]
```r
require(IRdisplay)
require(ggplot2)

df = data.frame(x = 1:5, y = 1:5)
myggplot = ggplot(df,
      aes(x = x, y = y)) +
geom_point()
print(myggplot)

prepare_mimebundle(myggplot)
```

Will return this 

```
$data
$data$`text/plain`
[1] ""


$metadata
NULL
```

And it should return an object with 

```
$data$`image/png` <representation of plot>
```

`prepare_mimebundle` loops over different mimetypes, and calls various forms of `repr_*` to populate `$data` and `$metadata`. This ggplot example will call `repr_png`. I believe the device is being triggered separately to render the image, but `repr_png`
https://github.com/IRkernel/repr/blob/6e1a943e4706e8044db228251bf46f201262b0e0/R/generics.r#L110 is returning NULL. The reason I want to be able to do this is to update the metadata.

**Comment by jeffwong** [comment]
If you are googling around, I found you have to pass 

```r
myggplot %>% print %>% renderPlot
```

Then repr_png will work!

**Comment by flying-sheep** [comment]
cool! thanks for researching and posting a followup!
