### ISSUE TITLE
Keep a NEWS or CHANGELOG file

### ISSUE THREAD

**Issue by cpsievert** [IRkernel/repr#92]
Otherwise it's hard to know what has changed from version to version

**Comment by flying-sheep** [comment]
I do this [here](https://github.com/IRkernel/repr/releases).

I don’t like to repeat myself, so is there a tool that creates those files from the github releases page?

**Comment by cpsievert** [comment]
> I don’t like to repeat myself, so is there a tool that creates those files from the github releases page?

I'm not sure, but perhaps just a link to the releases page would be helpful

**Comment by flying-sheep** [comment]
Fixed in 856e0cfa3f982c63afc64048abd87bd39d458174
